import {applyActivity,type Activity} from '../../lib/activity.ts';
import {applyPurpose,linkPurpose,type Purpose} from '../../lib/purposes.ts';
export type Energy='alta'|'media'|'baja';
export type Status='INBOX'|'PLANIFICADA'|'HOY'|'EN_CURSO'|'PAUSADA'|'BLOQUEADA'|'COMPLETADA'|'CANCELADA'|'ARCHIVADA';
export interface SupportLink{id:string;name:string;url:string}
export interface Task {supportVersion?:number;parentId?:string;supportLinks?:SupportLink[];id:string;title:string;description:string;area:string;projectId:string;status:Status;created:number;due:string;estimated:number;actual:number;importance:number;difficulty:number;resistance:number;energy:Energy;nextAction:string;steps:string[];stepsDone:number;completed?:number;points:number;xp:number;dependency:string}
export interface Reward{id:string;name:string;cost:number;category:string;emoji:string;goal:boolean}
export interface Project{id:string;name:string;area:string;description:string;purposeId?:string}
export interface Focus{taskId:string;started:number|null;seconds:number;target:number;kind:'normal'|'kickstart'}
export interface Day {missions:string[];done:string[];ordinary:number;xp:number;focusMinutes:number;focusXP:number;focus:boolean;bonus:boolean;win:boolean;protected:boolean;mood:string;tomorrow:string}
export interface State{activity?:Activity[];profile:{name:string;timezone:string;energy:Energy;onboarded:boolean};created:number;lastDay:string;xp:number;points:number;streak:number;best:number;shields:number;victories:number;areas:string[];tasks:Task[];projects:Project[];purposes?:Purpose[];rewards:Reward[];redemptions:{id:string;name:string;cost:number;at:number}[];sessions:{taskId:string;seconds:number;at:number;kind:string}[];days:Record<string,Day>;focus:Focus|null;applied:string[]}
export type Command={id:string;type:string;[key:string]:unknown};
export function dayKey(now:number,tz='America/Bogota'){return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now))}
const newDay=():Day=>({missions:[],done:[],ordinary:0,xp:0,focusMinutes:0,focusXP:0,focus:false,bonus:false,win:false,protected:false,mood:'',tomorrow:''});
export function fresh(now=Date.now()):State{const key=dayKey(now);return {profile:{name:'Jorge',timezone:'America/Bogota',energy:'media',onboarded:false},created:now,lastDay:key,xp:0,points:0,streak:0,best:0,shields:0,victories:0,areas:['Trabajo','Docencia','Maestría','Personal','Finanzas','Proyectos personales'],tasks:[],projects:[],purposes:[],rewards:[{id:'coffee',name:'Un café especial',cost:300,category:'Consumo',emoji:'☕',goal:false},{id:'movie',name:'Noche de película',cost:500,category:'Experiencias',emoji:'🍿',goal:false},{id:'food',name:'Mi comida favorita',cost:700,category:'Consumo',emoji:'🍜',goal:false},{id:'book',name:'Ese libro que quiero',cost:2000,category:'Productos',emoji:'📚',goal:false},{id:'headphones',name:'Mis próximos audífonos',cost:15000,category:'Productos',emoji:'🎧',goal:false}],redemptions:[],sessions:[],days:{[key]:newDay()},focus:null,applied:[]}}
export function level(xp:number){let l=1;while(xp>=50*l*(l+9))l++;return l}
export const threshold=(l:number)=>50*(l-1)*(l+8);
export const canonical=(s:string)=>s.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();
function text(v:unknown,max=160){if(typeof v!=='string')throw new Error('Escribe un texto válido.');const t=v.trim();if(!t||t.length>max)throw new Error('Revisa el texto: debe tener entre 1 y '+max+' caracteres.');return t}
function num(v:unknown,min:number,max:number,def:number){if(v===undefined||v==='')return def;const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error('El número debe estar entre '+min+' y '+max+'.');return n}
function optional(v:unknown,max=1000){return v===undefined||v===''?'':text(v,max)}
function energy(v:unknown):Energy{if(!['alta','media','baja'].includes(String(v)))throw new Error('Elige un nivel de energía.');return v as Energy}
export function nominal(t:Pick<Task,'importance'|'difficulty'|'resistance'>,minutes:number,deep:boolean){const base=minutes<=10?10:minutes<=25?20:minutes<=45?40:minutes<=90?70:100;return Math.min(150,base+(t.importance>=4?20:0)+(t.difficulty>=4?15:0)+(t.resistance>=4?15:0)+(deep?10:0))}
export function priority(t:Task,s:State,now=Date.now()){const age=Math.min(10,(now-t.created)/86400000);const delta=t.due?(Date.parse(t.due+'T12:00:00Z')-now)/86400000:Infinity;const urgency=delta<=0?30:delta<=1?25:delta<=3?20:delta<=7?10:0;const fit=t.energy===s.profile.energy?10:t.energy==='baja'?6:0;return urgency+t.importance*5+(t.projectId?15:5)+age+t.resistance*2+fit-(s.profile.energy==='baja'&&t.estimated>45?10:0)}
export function available(t:Task,s:State){return !t.parentId&&['PLANIFICADA','HOY','PAUSADA'].includes(t.status)&&(!t.dependency||s.tasks.some(x=>x.id===t.dependency&&x.status==='COMPLETADA'))}
export function plan(s:State,now=Date.now()){const list=s.tasks.filter(t=>available(t,s)).sort((a,b)=>priority(b,s,now)-priority(a,s,now));const main=list.find(t=>t.estimated>10)||list[0];const quick=list.find(t=>t.id!==main?.id&&t.estimated<=10);const progress=[...list].filter(t=>t.id!==main?.id&&t.id!==quick?.id).sort((a,b)=>(b.importance*5+(b.projectId?10:0))-(a.importance*5+(a.projectId?10:0)))[0];return [main?.id||'',quick?.id||'',progress?.id||'']}
function dateAfter(d:string){return new Date(Date.parse(d+'T12:00:00Z')+86400000).toISOString().slice(0,10)}
export function rollover(s:State,now:number){s.purposes??=[];s.activity??=[];const today=dayKey(now,s.profile.timezone);const closeUntil=(date:string)=>{while(s.lastDay<date){const d=s.days[s.lastDay];if(!d.win){if(s.streak>0&&s.shields>0){s.shields--;d.protected=true}else s.streak=0}s.lastDay=dateAfter(s.lastDay);s.days[s.lastDay]??=newDay()}};if(s.focus?.started!==null&&s.focus){const end=s.focus.started+(s.focus.target-s.focus.seconds)*1000;if(end<=now&&dayKey(end,s.profile.timezone)<today){closeUntil(dayKey(end,s.profile.timezone));finishFocus(s,end)}}closeUntil(today);const day=s.days[s.lastDay];if(!day.missions.some(Boolean)&&s.tasks.some(t=>available(t,s)))day.missions=plan(s,now);return s}
function checkDay(s:State){const d=s.days[s.lastDay];const main=!!d.missions[0]&&d.done.includes(d.missions[0]);const quick=d.done.some(id=>id!==d.missions[0]&&s.tasks.some(t=>t.id===id&&t.actual<=10));if(!d.win&&(main||d.done.length>=2||(d.focus&&d.done.length>=1))){d.win=true;s.streak++;s.victories++;s.best=Math.max(s.best,s.streak);if(s.victories%14===0)s.shields=Math.min(7,s.shields+1)}if(!d.bonus&&main&&quick&&d.focus){d.bonus=true;s.points+=50;s.xp+=50;d.xp+=50}}
export function elapsed(f:Focus,now:number){return Math.min(f.target,f.seconds+(f.started===null?0:Math.max(0,(now-f.started)/1000)))}
function finishFocus(s:State,now:number){if(!s.focus)return;const f=s.focus;const seconds=Math.floor(elapsed(f,now));const min=Math.floor(seconds/60);const d=s.days[s.lastDay];const xp=Math.min(min,Math.max(0,60-d.focusXP));s.xp+=xp;d.xp+=xp;d.focusXP+=xp;d.focusMinutes+=min;d.focus ||= min>=25;if(seconds>0)s.sessions.push({taskId:f.taskId,seconds,at:now,kind:f.kind});const task=s.tasks.find(t=>t.id===f.taskId);if(task&&task.status==='EN_CURSO')task.status='PAUSADA';s.focus=null;checkDay(s)}
function taskOf(s:State,id:unknown){const t=s.tasks.find(t=>t.id===id);if(!t)throw new Error('No encontramos esta misión. Actualiza la página.');return t}
export function childrenOf(s:State,id:string){return s.tasks.filter(t=>t.parentId===id)}
export function activeChildren(s:State,id:string){return childrenOf(s,id).filter(t=>!['CANCELADA','ARCHIVADA'].includes(t.status))}
function parentAvailable(s:State,t:Task){if(!t.parentId)return;const p=taskOf(s,t.parentId);if(p.completed||['CANCELADA','ARCHIVADA','BLOQUEADA'].includes(p.status))throw Error('La tarea principal no está disponible.');if(p.dependency&&!s.tasks.some(x=>x.id===p.dependency&&x.completed))throw Error('Completa primero la dependencia de la tarea principal.')}
function validateHierarchy(s:State){
 for(const t of s.tasks)if(t.parentId){const p=taskOf(s,t.parentId);if(p.id===t.id||p.parentId)throw Error('Usa una tarea principal y un solo nivel de subtareas.');if(t.area!==p.area||t.projectId!==p.projectId)throw Error('La subtarea debe pertenecer al proyecto y área de su principal.')}
 for(const parent of s.tasks){const children=new Set(childrenOf(s,parent.id).map(t=>t.id));const seen=new Set<string>();let dependency=parent.dependency;while(dependency&&!seen.has(dependency)){if(children.has(dependency))throw Error('La tarea principal no puede depender de una de sus subtareas.');seen.add(dependency);dependency=taskOf(s,dependency).dependency}}
 const visiting=new Set<string>(),visited=new Set<string>();
 const visit=(id:string)=>{if(visiting.has(id))throw Error('Las dependencias y subtareas no pueden formar un ciclo.');if(visited.has(id))return;visiting.add(id);const t=taskOf(s,id);if(t.dependency)visit(t.dependency);for(const c of childrenOf(s,id))visit(c.id);visiting.delete(id);visited.add(id)};for(const t of s.tasks)visit(t.id);
}
function taskFields(a:Record<string,unknown>,s:State){const parentId=optional(a.parentId,100);const parent=parentId?taskOf(s,parentId):undefined;if(parent&&s.focus?.taskId===parent.id)throw Error('Cierra el enfoque antes de añadir o editar subtareas.');if(parent&&(parent.parentId||parent.completed||['CANCELADA','ARCHIVADA'].includes(parent.status)))throw Error('Elige una tarea principal activa.');const area=parent?.area||optional(a.area,60)||(s.areas.includes('Personal')?'Personal':s.areas[0]);if(!s.areas.includes(area))throw new Error('Elige un área existente.');const projectId=parent?parent.projectId:optional(a.projectId,100);if(projectId&&!s.projects.some(p=>p.id===projectId))throw new Error('El proyecto no existe.');const due=optional(a.due,10);if(due&&(!/^\d{4}-\d{2}-\d{2}$/.test(due)||new Date(due).toISOString().slice(0,10)!==due))throw new Error('Revisa la fecha.');let steps:string[]=[];if(Array.isArray(a.steps)){if(a.steps.length>20)throw new Error('Usa hasta 20 pasos.');steps=a.steps.map(x=>text(x,200))}const dependency=optional(a.dependency,100);if(dependency&&!s.tasks.some(t=>t.id===dependency))throw new Error('La dependencia no existe.');return {parentId,title:text(a.title),description:optional(a.description),area,projectId,due,estimated:num(a.minutes,1,480,25),importance:num(a.importance,1,5,3),difficulty:num(a.difficulty,1,5,2),resistance:num(a.resistance,1,5,1),energy:a.energy?energy(a.energy):'media' as Energy,nextAction:optional(a.nextAction,300),steps,dependency}}
export function apply(input:State,a:Command,now=Date.now()):State{if(!a.id||typeof a.id!=='string'||a.id.length>100)throw new Error('Identificador inválido.');const s=rollover(structuredClone(input),now);if(s.applied.includes(a.id))return s;const activity=applyActivity(s,a,now,apply);if(activity)return activity;const d=s.days[s.lastDay];
switch(a.type){
case 'purpose':applyPurpose(s,a);break;
case 'linkPurpose':linkPurpose(s,a);break;
case 'assistDay':{if(s.focus)throw Error('Cierra tu sesión de enfoque antes de cambiar el plan.');if(!Array.isArray(a.taskIds)||a.taskIds.length<1||a.taskIds.length>3||new Set(a.taskIds).size!==a.taskIds.length)throw Error('Elige entre una y tres misiones distintas.');const selected=a.taskIds.map(id=>taskOf(s,id));if(selected.some(t=>t.parentId||t.completed||['EN_CURSO','COMPLETADA','CANCELADA','ARCHIVADA','BLOQUEADA'].includes(t.status)||(t.dependency&&!s.tasks.some(d=>d.id===t.dependency&&d.completed))))throw Error('Elige misiones disponibles y sin bloqueos.');const completed=d.missions.filter(id=>id&&!!s.tasks.find(t=>t.id===id)?.completed);if(completed.length+selected.length>3)throw Error('El plan debe conservar los espacios completados del día.');const previous=d.missions;let cursor=0;d.missions=[0,1,2].map(i=>completed.includes(previous[i])?previous[i]:selected[cursor++]?.id||'');for(const t of s.tasks){if(selected.some(x=>x.id===t.id))t.status='HOY';else if(previous.includes(t.id)&&t.status==='HOY')t.status='PLANIFICADA'}break}
case 'supportIntent':{const t=taskOf(s,a.taskId);if(['ARCHIVADA','CANCELADA'].includes(t.status))throw Error('No puedes subir soportes a una tarea archivada.');if((t.supportVersion||0)>=Number.MAX_SAFE_INTEGER)throw Error('Demasiadas operaciones de soportes.');t.supportVersion=(t.supportVersion||0)+1;break}
case 'reopenSubtask':{const t=taskOf(s,a.taskId);if(!t.parentId||t.points||t.xp)throw Error('Solo puedes corregir el avance de una subtarea sin recompensas.');parentAvailable(s,t);delete t.completed;t.status='INBOX';t.actual=0;break}
case 'reparent':{const t=taskOf(s,a.taskId);if(t.completed||childrenOf(s,t.id).length)throw Error('No conviertas tareas completadas o con subtareas.');if(s.focus?.taskId===t.id||(t.parentId&&s.focus?.taskId===t.parentId))throw Error('Termina o pausa y cierra el enfoque antes de reorganizar.');const parentId=optional(a.parentId,100);if(parentId){const p=taskOf(s,parentId);if(p.id===t.id||p.parentId||p.completed||['ARCHIVADA','CANCELADA'].includes(p.status))throw Error('Elige otra tarea principal activa.');if(s.focus?.taskId===p.id)throw Error('Cierra el enfoque de la tarea principal antes de reorganizar.');t.area=p.area;t.projectId=p.projectId;}t.parentId=parentId;validateHierarchy(s);d.missions=d.missions.map(id=>id===t.id?'':id);break}
case 'supportLink':{const t=taskOf(s,a.taskId);const url=text(a.url,2000);let parsed:URL;try{parsed=new URL(url)}catch{throw Error('Escribe un enlace válido.')}if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Usa un enlace http o https sin credenciales.');if((t.supportLinks?.length||0)>=20)throw Error('Usa hasta 20 enlaces por tarea.');t.supportLinks??=[];t.supportLinks.push({id:crypto.randomUUID(),name:text(a.name,160),url:parsed.href});break}
case 'removeSupportLink':{const t=taskOf(s,a.taskId);t.supportLinks=(t.supportLinks||[]).filter(link=>link.id!==a.linkId);break}
case 'assistSteps':{const t=taskOf(s,a.taskId);if(t.completed||['COMPLETADA','ARCHIVADA','CANCELADA'].includes(t.status))throw new Error('Esta misión conserva su historial.');if(t.stepsDone>0)throw new Error('Ya avanzaste en los pasos. Revisa los cambios desde Editar misión.');if(!Array.isArray(a.steps)||!a.steps.length||a.steps.length>8)throw new Error('Revisa los pasos propuestos.');t.nextAction=text(a.nextAction,300);t.steps=a.steps.map(x=>text(x,200));break}
case 'capture':{if(!Array.isArray(a.tasks)||a.tasks.length<1||a.tasks.length>30)throw new Error('Captura entre 1 y 30 tareas.');if(s.tasks.length+a.tasks.length>1500)throw new Error('Has alcanzado el límite de 1.500 tareas.');for(const raw of a.tasks){if(!raw||typeof raw!=='object')throw new Error('Tarea inválida.');const fields=taskFields(raw as Record<string,unknown>,s);if(s.tasks.some(t=>canonical(t.title)===canonical(fields.title)&&!['COMPLETADA','CANCELADA','ARCHIVADA'].includes(t.status)))throw new Error('Ya existe una misión pendiente con ese título: '+fields.title);s.tasks.push({id:crypto.randomUUID(),...fields,status:'INBOX',created:now,actual:0,stepsDone:0,points:0,xp:0})}validateHierarchy(s);break}
case 'editTask':{const t=taskOf(s,a.taskId);if(t.completed)throw new Error('Una misión completada conserva su historial.');const fields=taskFields({...a,parentId:t.parentId},s);if(t.steps.slice(0,t.stepsDone).some((step,i)=>fields.steps[i]!==step))throw new Error('Conserva los pasos completados; solo puedes editar los pendientes.');if(fields.dependency===t.id)throw new Error('Una tarea no puede depender de sí misma.');let dep=fields.dependency;const visited=new Set([t.id]);while(dep){if(visited.has(dep))throw new Error('Las dependencias no pueden formar un ciclo.');visited.add(dep);dep=s.tasks.find(x=>x.id===dep)?.dependency||''}Object.assign(t,fields);t.stepsDone=Math.min(t.stepsDone,t.steps.length);for(const c of childrenOf(s,t.id)){c.area=t.area;c.projectId=t.projectId}validateHierarchy(s);break}
case 'status':{const t=taskOf(s,a.taskId);if(t.completed)throw new Error('La misión ya está completada.');if(!['INBOX','PLANIFICADA','HOY','BLOQUEADA','CANCELADA','ARCHIVADA'].includes(String(a.status)))throw new Error('Estado inválido.');if(s.focus&&(s.focus.taskId===t.id||s.tasks.find(x=>x.id===s.focus?.taskId)?.parentId===t.id))finishFocus(s,now);t.status=a.status as Status;d.missions=d.missions.map(id=>id===t.id?'':id);break}
case 'plan':{for(const t of s.tasks)if(t.status==='INBOX')t.status='PLANIFICADA';const selected=plan(s,now);if(!d.missions.some(Boolean))d.missions=selected;else{const used=new Set(d.missions);d.missions=[0,1,2].map(i=>{const old=d.missions[i];if(old)return old;const candidate=s.tasks.filter(t=>available(t,s)&&!used.has(t.id)&&(i!==1||t.estimated<=10)).sort((a,b)=>priority(b,s,now)-priority(a,s,now))[0];if(candidate){used.add(candidate.id);return candidate.id}return ''})}for(const t of s.tasks)if(d.missions.includes(t.id)&&available(t,s))t.status='HOY';break}
case 'replace':{const slot=num(a.slot,0,2,0);const candidate=s.tasks.filter(t=>available(t,s)&&!d.missions.includes(t.id)&&(slot!==1||t.estimated<=10)).sort((x,y)=>priority(y,s,now)-priority(x,s,now))[0];if(!candidate)throw new Error('No hay otra misión disponible para este espacio.');const old=s.tasks.find(t=>t.id===d.missions[slot]);if(old?.completed)throw new Error('Esta misión ya forma parte de tu progreso de hoy.');d.missions[slot]=candidate.id;candidate.status='HOY';break}
case 'energy':s.profile.energy=energy(a.value);break;
case 'profile':s.profile.name=text(a.name,60);s.profile.onboarded=true;break;
case 'area':{const name=text(a.name,60);if(s.areas.includes(name))throw new Error('El área ya existe.');if(a.oldName){const old=text(a.oldName,60);if(!s.areas.includes(old))throw new Error('El área no existe.');s.areas=s.areas.map(x=>x===old?name:x);for(const t of s.tasks)if(t.area===old)t.area=name;for(const p of s.projects)if(p.area===old)p.area=name;for(const p of s.purposes||[])if(p.area===old)p.area=name}else s.areas.push(name);break}
case 'project':{const name=text(a.name);const area=text(a.area,60);if(!s.areas.includes(area))throw new Error('Área inválida.');if(s.projects.length>=100)throw new Error('Máximo 100 proyectos.');s.projects.push({id:crypto.randomUUID(),name,area,description:optional(a.description)});break}
case 'start':{if(s.focus)throw new Error('Ya tienes una sesión abierta.');const t=taskOf(s,a.taskId);parentAvailable(s,t);if(t.completed||['CANCELADA','ARCHIVADA','BLOQUEADA'].includes(t.status))throw new Error('Esta tarea no está disponible.');if(t.dependency&&!s.tasks.some(x=>x.id===t.dependency&&x.completed))throw new Error('Completa primero la tarea de la que depende.');const kind=a.kind==='kickstart'?'kickstart':'normal';s.focus={taskId:t.id,started:now,seconds:0,target:kind==='kickstart'?300:Math.min(90,t.estimated)*60,kind};t.status='EN_CURSO';break}
case 'pause':if(s.focus){s.focus.seconds=elapsed(s.focus,now);s.focus.started=null}break;
case 'resume':if(s.focus&&s.focus.started===null)s.focus.started=now;break;
case 'extend':if(!s.focus)throw new Error('No hay una sesión abierta.');s.focus.seconds=elapsed(s.focus,now);s.focus.target+=600;s.focus.started=now;break;
case 'finishFocus':finishFocus(s,now);break;
case 'step':{const t=taskOf(s,a.taskId);if(t.completed)throw Error('La misión ya está completada.');t.stepsDone=Math.min(t.steps.length,t.stepsDone+1);break}
case 'complete':{const t=taskOf(s,a.taskId);if(t.completed)break;parentAvailable(s,t);const children=activeChildren(s,t.id);if(children.some(c=>!c.completed))throw Error('Completa las subtareas pendientes antes de confirmar el resultado.');if(childrenOf(s,t.id).length&&a.resultConfirmed!==true)throw Error('Confirma explícitamente que el resultado está terminado.');if(t.stepsDone<t.steps.length)throw Error('Completa primero los pasos pendientes.');if(['CANCELADA','ARCHIVADA','BLOQUEADA'].includes(t.status))throw new Error('Esta tarea no se puede completar.');if(t.dependency&&!s.tasks.some(x=>x.id===t.dependency&&x.completed))throw new Error('Completa primero la dependencia.');if(s.focus?.taskId===t.id)finishFocus(s,now);const tracked=Math.ceil(s.sessions.filter(x=>x.taskId===t.id).reduce((n,x)=>n+x.seconds,0)/60);const minutes=num(a.minutes,1,10080,Math.min(10080,tracked||t.estimated));const duplicate=s.tasks.some(x=>x.id!==t.id&&x.completed&&dayKey(x.completed,s.profile.timezone)===s.lastDay&&canonical(x.title)===canonical(t.title));const deep=s.sessions.some(x=>x.taskId===t.id&&x.seconds>=1500);const value=t.parentId||duplicate?0:nominal(t,minutes,deep);const pts=Math.max(0,Math.min(value,300-d.ordinary));t.status='COMPLETADA';t.completed=now;t.actual=minutes;t.stepsDone=t.steps.length;t.points=pts;t.xp=value;s.points+=pts;s.xp+=value;d.ordinary+=pts;d.xp+=value;if(!duplicate&&!t.parentId)d.done.push(t.id);checkDay(s);break}
case 'reward':{const reward={id:crypto.randomUUID(),name:text(a.name,100),cost:num(a.cost,1,1000000,300),category:text(a.category,60),emoji:optional(a.emoji,12)||'🎁',goal:false};if(a.rewardId){const old=s.rewards.find(r=>r.id===a.rewardId);if(!old)throw new Error('La recompensa no existe.');Object.assign(old,{...reward,id:old.id,goal:old.goal})}else s.rewards.push(reward);break}
case 'goal':{if(!s.rewards.some(r=>r.id===a.rewardId))throw new Error('La recompensa no existe.');for(const r of s.rewards)r.goal=r.id===a.rewardId;break}
case 'redeem':{if(s.redemptions.some(r=>r.id===a.id))break;const r=s.rewards.find(r=>r.id===a.rewardId);if(!r)throw new Error('La recompensa no existe.');if(s.points<r.cost)throw new Error('Todavía no tienes suficientes puntos.');s.points-=r.cost;s.redemptions.push({id:a.id,name:r.name,cost:r.cost,at:now});break}
case 'closeDay':{if(!['Difícil','Normal','Bien','Excelente'].includes(String(a.mood)))throw new Error('Elige cómo sentiste el día.');d.mood=String(a.mood);d.tomorrow=optional(a.tomorrow,200);break}
default:throw new Error('Acción no reconocida.');
}s.applied.push(a.id);s.applied=s.applied.slice(-200);return s}
export function parseDump(value:string){return value.replace(/^\s*(debo|tengo que|necesito)\s+/i,'').split(/[,;\n]+|\s+y\s+(?=(?:comprar|llamar|revisar|enviar|preparar|leer|hacer|pagar|responder|escribir)\b)/i).map(x=>x.trim().replace(/[.]+$/,'')).filter(Boolean).slice(0,30).map(title=>({title:title.charAt(0).toUpperCase()+title.slice(1),area:/clase|alumno|docen/i.test(title)?'Docencia':/tesis|art[ií]culo|maestr|marco te[oó]rico/i.test(title)?'Maestría':/factura|pagar|banco/i.test(title)?'Finanzas':/contrato|cliente|tutela|concepto/i.test(title)?'Trabajo':'Personal',minutes:/llamar|correo|comprar/i.test(title)?10:25}))}



