'use client';
import {useEffect,useState} from 'react';
import {History,Undo2,Download,ChevronLeft,ChevronRight} from 'lucide-react';
import type {State,Task} from '../lib/domain';
import type {Act} from './useQuest';
type RemoteRow={id:string;kind:string;source:'text'|'voice';revision:number;status:string;summary:string;code?:string|null;created_at:string};
const labels:Record<string,string>={executed:'Ejecutada',undone:'Deshecha',pending:'Propuesta pendiente',failed:'Fallida',rejected:'Rechazada'};
export default function Activity({s,act,busy,error,open,project}:{s:State;act:Act;busy:boolean;error:string;open?:(task:Task)=>void;project?:(id:string)=>void}){
 const [page,setPage]=useState(0),[rows,setRows]=useState<RemoteRow[]>([]),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[remoteError,setRemoteError]=useState('');
 const committed=s.activity||[],count=committed.length,items=[...committed].reverse().slice(page*20,(page+1)*20);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setRemoteError('');void fetch('/api/activity?page='+page,{cache:'no-store',signal:controller.signal}).then(async res=>{if(!res.ok)throw Error('No se pudieron cargar las propuestas y los fallos.');const data=await res.json() as {rows:RemoteRow[];hasMore:boolean};setRows(data.rows);setHasMore(data.hasMore);}).catch(e=>{if(!controller.signal.aborted)setRemoteError(e instanceof Error?e.message:'No se pudo cargar la actividad.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort();},[page,s.activity]);
 const operationIds=new Set(committed.map(event=>event.id)),remote=rows.filter(row=>!operationIds.has(row.id));
 return <section className="activity-panel"><div className="spread"><div><p className="eyebrow">TU ESPACIO PRIVADO</p><h2><History size={22}/> Actividad de Balta</h2></div><a className="button secondary" href="/api/activity?export=1"><Download size={16}/>Exportar operaciones</a></div>
  <p className="muted">Acciones guardadas y propuestas de texto o voz. Deshacer comprueba que no haya cambios posteriores; las tareas creadas se conservan como archivadas.</p>
  {(error||remoteError)&&<p className="error-inline" role="alert">{error||remoteError}</p>}
  <div className="activity-list">{items.map(event=><article className="panel activity-item" key={event.id}><div className="spread"><strong>{labels[event.status]}</strong><span className="small muted">{event.source==='voice'?'Voz':'Texto'} · {new Date(event.at).toLocaleString('es-CO',{timeZone:s.profile.timezone})}</span></div><p>{event.summary}</p><p className="small muted">{event.tool==='capture'?'Creación de pendientes':event.tool==='assistDay'?'Plan del día':'Vínculo de propósito'} · {event.id}</p>{event.receipt.kind==='linkPurpose'?project&&<button className="text-button" onClick={()=>project(event.receipt.kind==='linkPurpose'?event.receipt.projectId:'')}>Revisar proyecto</button>:open&&event.receipt.tasks.length>0&&<button className="text-button" onClick={()=>{if(event.receipt.kind==='linkPurpose')return;const taskId=event.receipt.tasks[0]?.id;const task=s.tasks.find(t=>t.id===taskId);if(task)open(task)}}>Revisar elemento</button>}{event.status==='executed'?<button className="button secondary" disabled={busy} onClick={()=>{void act({type:'undoBalta',operationId:event.id})}}><Undo2 size={16}/>Deshacer</button>:<p className="small muted">Deshecha el {new Date(event.undoneAt!).toLocaleString('es-CO',{timeZone:s.profile.timezone})}.</p>}</article>)}
  {remote.map(row=><article className="panel activity-item" key={row.id}><div className="spread"><strong>{labels[row.status]||row.status}</strong><span className="small muted">{row.source==='voice'?'Voz':'Texto'} · {new Date(row.created_at).toLocaleString('es-CO',{timeZone:s.profile.timezone})}</span></div><p>{row.summary}</p><p className="small muted">{row.id}{row.code?' · '+row.code:''}</p>{row.status==='pending'&&<p className="hint">Esta propuesta todavía no produjo cambios.</p>}</article>)}</div>
  {!items.length&&!remote.length&&!loading&&<p className="muted">No hay operaciones en esta página.</p>}{loading&&<p className="small muted" role="status">Cargando operaciones…</p>}
  <nav className="spread" aria-label="Páginas de actividad"><button className="button secondary" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>Anterior</button><span className="small">Página {page+1}</span><button className="button secondary" disabled={loading||((page+1)*20>=count&&!hasMore)} onClick={()=>setPage(p=>p+1)}>Siguiente<ChevronRight size={16}/></button></nav>
  <p className="small muted">Se conservan los 200 comprobantes recientes. Las propuestas y los fallos corresponden a los últimos 90 días y se exportan por separado.</p>
 </section>;
}
