'use client';
import {useState,useEffect} from 'react';
import {Sparkles,Trash2,Check} from 'lucide-react';
import type {State} from '../lib/domain';
import type {Proposal} from '../../lib/assistant';
import type {Act} from './useQuest';
import {useAssistant} from './useAssistant';
import {AssistantConsent,AssistantStatus,AssistantQuestions,AssistantHeading} from './AssistantCommon';
export default function AssistantCapture({s,revision,refresh,act,busy,close,error}:{s:State;revision:number;refresh:()=>Promise<void>;act:Act;busy:boolean;close:()=>void;error:string}){
 const a=useAssistant(revision,refresh),[text,setText]=useState(''),[rows,setRows]=useState<Proposal['tasks']>([]);
 useEffect(()=>setRows(a.result?.proposal.tasks||[]),[a.result]);
 const update=(i:number,patch:Partial<Proposal['tasks'][number]>)=>setRows(rows.map((r,j)=>i===j?{...r,...patch}:r));
 const stale=!!a.result&&revision!==a.result.revision;
 return <section className="assistant-capture"><AssistantHeading subtitle="Saca tus pendientes de la cabeza. Revisaremos cada acción antes de guardarla."/><label>¿Qué necesitas organizar?<textarea rows={5} value={text} maxLength={5000} placeholder="Tengo que preparar la clase, revisar la propuesta y sacar tiempo para estudiar…" onChange={e=>{setText(e.target.value);a.reset()}} disabled={a.busy}/></label><AssistantConsent a={a} context="este texto, tus áreas y los nombres de tus proyectos"/><button type="button" className="button" disabled={busy||a.busy||!a.consent||!text.trim()} onClick={()=>a.ask({kind:'capture',text})}><Sparkles size={17}/>Organizar con Balthazar</button><AssistantStatus a={a}/>{a.result&&<><p className="assistant-summary">{a.result.proposal.summary}</p><AssistantQuestions questions={a.result.proposal.questions}/><div className="assistant-drafts">{rows.map((r,i)=><article className="assistant-draft" key={i}><div className="spread"><strong className="eyebrow">PROPUESTA DE MISIÓN</strong><button type="button" className="icon-button" aria-label={'Quitar propuesta '+(i+1)} onClick={()=>setRows(rows.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div><label>Título<input required maxLength={160} value={r.title} onChange={e=>update(i,{title:e.target.value})}/></label><div className="form-grid"><label>Área<select value={r.area} onChange={e=>update(i,{area:e.target.value,projectId:''})}>{s.areas.map(x=><option key={x}>{x}</option>)}</select></label><label>Minutos estimados<input type="number" min={1} max={480} value={r.minutes} onChange={e=>update(i,{minutes:Number(e.target.value)})}/></label></div><label>Proyecto<select value={r.projectId} onChange={e=>update(i,{projectId:e.target.value})}><option value="">Sin proyecto</option>{s.projects.filter(p=>p.area===r.area).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Fecha límite<input type="date" value={r.due} onChange={e=>update(i,{due:e.target.value})}/></label><label>Siguiente acción<input maxLength={300} value={r.nextAction} onChange={e=>update(i,{nextAction:e.target.value})}/></label></article>)}</div>{stale&&<p className="hint">Tu espacio cambió. Consulta de nuevo antes de guardar estas propuestas.</p>}{rows.length>0&&<button type="button" className="button full" disabled={busy||stale||rows.some(r=>!r.title.trim()||!r.nextAction.trim()||!Number.isInteger(r.minutes)||r.minutes<1||r.minutes>480)} onClick={async()=>{if(await act({type:'capture',tasks:rows},a.result!.revision))close()}}><Check size={17}/>Guardar {rows.length} {rows.length===1?'tarea':'tareas'} en mi Inbox</button>}</>}{error&&<p role="alert" className="error-inline">{error}</p>}</section>
}
