'use client';
import {useState} from 'react';
import {Plus,Search,Inbox,Play,Check,Folder,Lock,Archive,Sparkles,Paperclip} from 'lucide-react';
import {activeChildren,childrenOf,type State,type Task} from '../lib/domain';
import type {Act} from './useQuest';
export default function Missions({s,act,busy,capture,edit,start,complete,newProject,assist,initialProject='',initialTab='Activas',onProjectChange}:{initialProject?:string;initialTab?:string;onProjectChange?:(id:string)=>void;assist:(t:Task)=>void;s:State;act:Act;busy:boolean;capture:(id?:string)=>void;edit:(t:Task)=>void;start:(t:Task,kind?:string)=>void;complete:(id:string)=>void;newProject:()=>void}){
 const [tab,setTab]=useState(initialTab),[search,setSearch]=useState(''),[area,setArea]=useState('Todas'),[project,setProject]=useState(initialProject);
 const selectProject=(id:string)=>{setProject(id);onProjectChange?.(id)};
 const query=search.trim().toLocaleLowerCase('es');
 const matches=(t:Task)=>t.title.toLocaleLowerCase('es').includes(query)||childrenOf(s,t.id).some(c=>c.title.toLocaleLowerCase('es').includes(query));
 const list=s.tasks.filter(t=>!t.parentId&&(tab==='Inbox'?t.status==='INBOX':tab==='Completadas'?t.status==='COMPLETADA':tab==='Archivadas'?['ARCHIVADA','CANCELADA'].includes(t.status):!['COMPLETADA','CANCELADA','ARCHIVADA'].includes(t.status))&&(area==='Todas'||t.area===area)&&(!project||t.projectId===project)&&matches(t)).sort((a,b)=>b.created-a.created);
 function row(t:Task){const blocked=t.status==='BLOQUEADA'||!!t.dependency&&!s.tasks.some(x=>x.id===t.dependency&&x.completed),children=activeChildren(s,t.id),done=children.filter(c=>c.completed).length;
  return <article className="task-row" key={t.id}><button className={'task-check '+(t.completed?'checked':'')} aria-label={'Revisar resultado de '+t.title} disabled={busy||!!t.completed||!!blocked} onClick={()=>children.some(c=>!c.completed)||t.stepsDone<t.steps.length?edit(t):complete(t.id)}>{t.completed?<Check size={16}/>:blocked?<Lock size={13}/>:null}</button><button className="task-description" onClick={()=>edit(t)}><strong>{t.title}</strong><span>{t.area} · {t.estimated} min{t.due?' · Vence '+t.due:''}{blocked?t.status==='BLOQUEADA'?' · Bloqueada':' · Esperando una tarea':''}</span>{children.length>0&&<span className={done===children.length&&!t.completed?'green':''}>{done} de {children.length} subtareas completadas{done===children.length&&!t.completed?' · Confirma el resultado':''}</span>}{!!t.supportLinks?.length&&<span><Paperclip size={12}/> {t.supportLinks.length} enlaces</span>}</button>{!t.completed&&!['ARCHIVADA','CANCELADA'].includes(t.status)&&<div className="row-actions"><button className="icon-button assistant-task-button" aria-label={'Ayúdame a empezar: '+t.title} disabled={busy} onClick={()=>assist(t)}><Sparkles size={17}/></button><button className="icon-button" aria-label={'Empezar '+t.title} disabled={busy||!!blocked||t.status==='BLOQUEADA'} onClick={()=>start(t)}><Play size={17}/></button><button className="icon-button" aria-label={'Archivar '+t.title} disabled={busy} onClick={()=>act({type:'status',taskId:t.id,status:'ARCHIVADA'})}><Archive size={17}/></button></div>}{t.completed&&<span className="points-pill">+{t.points} pts</span>}{['ARCHIVADA','CANCELADA'].includes(t.status)&&<button className="text-button" disabled={busy} onClick={()=>act({type:'status',taskId:t.id,status:'INBOX'})}>Restaurar</button>}</article>
 }
 const groups=[...s.projects.map(p=>({id:p.id,name:p.name})),{id:'',name:'Sin proyecto'}].map(g=>({...g,tasks:list.filter(t=>t.projectId===g.id)})).filter(g=>g.tasks.length);
 return <><div className="page-tools"><div className="tabs">{['Activas','Inbox','Proyectos','Completadas','Archivadas'].map(x=><button key={x} className={tab===x?'selected':''} onClick={()=>{setTab(x);selectProject('')}}>{x}{x==='Inbox'&&<span className="count">{s.tasks.filter(t=>!t.parentId&&t.status==='INBOX').length}</span>}</button>)}</div><button className="button" onClick={()=>tab==='Proyectos'?newProject():capture()}><Plus size={18}/>{tab==='Proyectos'?'Nuevo proyecto':'Nueva misión'}</button></div>
 {tab==='Proyectos'&&!project?<div className="project-grid">{s.projects.map(p=>{const tasks=s.tasks.filter(t=>!t.parentId&&t.projectId===p.id&&!['ARCHIVADA','CANCELADA'].includes(t.status)),completed=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(completed/tasks.length*100):0;return <button className="card project-card" key={p.id} onClick={()=>selectProject(p.id)}><div className="eyebrow"><Folder size={18}/>{p.area}</div><h3>{p.name}</h3><p>{p.description||'Cada acción acerca este proyecto a la meta.'}</p><div className="progress"><i style={{width:pct+'%'}}/></div><div className="spread small"><span>{completed} de {tasks.length} misiones</span><strong>{pct}%</strong></div></button>})}{!s.projects.length&&<div className="empty"><Folder/><h3>Un gran proyecto, pequeños pasos.</h3><button className="button" onClick={newProject}>Crear proyecto</button></div>}</div>:<>
 {project&&<div className="section-title"><button className="text-button" onClick={()=>{selectProject('');setTab('Proyectos')}}>Volver a proyectos</button><h2>{s.projects.find(p=>p.id===project)?.name}</h2><button className="button secondary" onClick={()=>capture(project)}>Añadir misión</button></div>}
 <p className="muted small">{list.length} tareas principales · Las subtareas y soportes están dentro de cada misión.</p>
 <div className="filters"><div className="search"><Search size={18}/><input aria-label="Buscar misiones y subtareas" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar misiones o subtareas…"/></div><select aria-label="Filtrar por área" value={area} onChange={e=>setArea(e.target.value)}><option>Todas</option>{s.areas.map(x=><option key={x}>{x}</option>)}</select>{tab==='Inbox'&&list.length>0&&<button className="button secondary" disabled={busy} onClick={()=>act({type:'plan'})}>Preparar misiones</button>}</div>
 {groups.map(g=><details className="mission-group" key={g.id+tab+project+!!query} open={query||project?true:undefined}><summary><Folder size={18}/><strong>{g.name}</strong><span>{g.tasks.length} {g.tasks.length===1?'misión':'misiones'}</span></summary><div className="task-list">{g.tasks.map(row)}</div></details>)}
 {!list.length&&<div className="empty"><Inbox/><h3>{tab==='Completadas'?'Aquí vivirán tus avances.':'Todo tiene su momento.'}</h3><p>{search?'No hay misiones o subtareas que coincidan.':'Las misiones de esta sección aparecerán aquí.'}</p>{tab!=='Completadas'&&!search&&<button className="button secondary" onClick={()=>capture(project)}>Capturar una tarea</button>}</div>}
 </>}</>;
}
