'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Task} from '../lib/domain';
import type {Act} from './useQuest';
import {MAX_SUPPORT_FILES,validateSupportFile,type SupportFile} from '../../lib/supports';
export default function SupportPanel({task,act,busy}:{task:Task;act:Act;busy:boolean}){
 const [files,setFiles]=useState<SupportFile[]>([]),[error,setError]=useState(''),[working,setWorking]=useState(false),[loading,setLoading]=useState(true),[deleteId,setDeleteId]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState('');
 const pending=useRef(false),input=useRef<HTMLInputElement>(null);
 const endpoint=useCallback((file?:string)=>`/api/supports?task=${encodeURIComponent(task.id)}${file?`&file=${encodeURIComponent(file)}`:''}`,[task.id]);
 async function reply(res:Response){if(res.redirected||!res.headers.get('content-type')?.includes('application/json'))throw Error('Vuelve a entrar para acceder a tus soportes.');const data=await res.json();if(!res.ok)throw Error(data.error||'No se pudo procesar el soporte.');return data;}
 const load=useCallback(async(signal?:AbortSignal)=>{const res=await fetch(endpoint(),{cache:'no-store',signal});return (await reply(res)).files as SupportFile[]},[endpoint]);
 useEffect(()=>{const controller=new AbortController();setFiles([]);setError('');setLoading(true);void load(controller.signal).then(setFiles).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'No se pudieron cargar los soportes.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[load]);
 async function run(action:()=>Promise<void>){if(pending.current||busy)return;pending.current=true;setWorking(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'No se pudo procesar el soporte.')}finally{pending.current=false;setWorking(false)}}
 const disabled=busy||working;
 return <section className="support-panel"><h3>Soportes</h3><p className="small muted">Archivos privados opcionales, hasta 8 MB y veinte por misión. Se descargan como archivos y no se envían a IA.</p>
 {error&&<p role="alert" className="error">{error}</p>}
 <form onSubmit={e=>{e.preventDefault();void run(async()=>{let parsed:URL;try{parsed=new URL(url)}catch{throw Error('Escribe un enlace HTTP o HTTPS válido.')}if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Escribe un enlace HTTP o HTTPS sin credenciales.');if(!name.trim())throw Error('Escribe un nombre para el enlace.');if(await act({type:'supportLink',taskId:task.id,name:name.trim(),url:parsed.href})){setName('');setUrl('')}else throw Error('No se pudo guardar el enlace. Revisa el mensaje de la misión.')})}}>
 <label>Nombre del enlace<input value={name} maxLength={160} onChange={e=>setName(e.target.value)} disabled={disabled} placeholder="Informe, entrega o referencia" required/></label>
 <label>Enlace<input type="url" value={url} maxLength={2000} onChange={e=>setUrl(e.target.value)} disabled={disabled} placeholder="https://…" required/></label>
 <button className="button secondary" disabled={disabled}>Añadir enlace</button></form>
 {(task.supportLinks||[]).map(link=><div className="spread" key={link.id}><a href={link.url} target="_blank" rel="noopener noreferrer">{link.name}</a><button className="text-button" disabled={disabled} onClick={()=>void run(async()=>{if(!await act({type:'removeSupportLink',taskId:task.id,linkId:link.id}))throw Error('No se pudo quitar el enlace.')})}>Quitar enlace</button></div>)}
 <label>Adjuntar archivo<input ref={input} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.docx,.xlsx,.pptx" disabled={disabled||loading||files.length>=MAX_SUPPORT_FILES} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void run(async()=>{validateSupportFile(file,files.length);const form=new FormData();form.set('task',task.id);form.set('file',file);await reply(await fetch('/api/supports',{method:'POST',body:form}));setFiles(await load())}).finally(()=>{window.dispatchEvent(new Event('balthazar-space-changed'));if(input.current)input.current.value=''})}}/></label>
 {loading?<p role="status">Cargando archivos…</p>:<p className="small muted">{files.length} de veinte archivos · PDF, PNG, JPG, WEBP, TXT, DOCX, XLSX y PPTX.</p>}
 {files.map(file=><div className="spread" key={file.id}><span style={{overflowWrap:'anywhere'}}>{file.name} <small>({Math.ceil(file.size/1024)} KB)</small></span><div className="row-actions"><button className="text-button" disabled={disabled} onClick={()=>void run(async()=>{const res=await fetch(endpoint(file.id),{cache:'no-store'});if(!res.ok){await reply(res);return}if(res.redirected||!res.headers.get('content-disposition')?.startsWith('attachment'))throw Error('Vuelve a entrar para descargar el archivo.');const blob=await res.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000)})}>Descargar</button>{deleteId===file.id?<><button className="text-button" disabled={disabled} onClick={()=>void run(async()=>{await reply(await fetch(endpoint(file.id),{method:'DELETE'}));setDeleteId('');setFiles(await load())})}>Confirmar eliminar</button><button className="text-button" disabled={disabled} onClick={()=>setDeleteId('')}>Cancelar</button></>:<button className="text-button" disabled={disabled} onClick={()=>setDeleteId(file.id)}>Eliminar archivo</button>}</div></div>)}
 <p className="small muted">El respaldo JSON conserva los enlaces; los archivos necesitan un respaldo independiente de Storage.</p></section>
}

