'use client';
import {Target,Zap,Sprout,Play,Plus,Clock,Compass,Check,Flame,Shield,RefreshCw,LifeBuoy,ArrowUpRight,Gift,Moon,Inbox,Sparkles} from 'lucide-react';
import DailyProtocol from './DailyProtocol';
import MissionExecution from './MissionExecution';
import {inboxCount} from '../../lib/execution';
import type {State,Task} from '../lib/domain';import {nominal} from '../lib/domain';import type {Act} from './useQuest';
export default function Today({s,act,busy,capture,start,closeDay,rescue,assist,open,complete}:{open:(t:Task)=>void;complete:(id:string)=>void;assist:(t:Task)=>void;s:State;act:Act;busy:boolean;capture:()=>void;start:(t:Task,kind?:string)=>void;closeDay:()=>void;rescue:()=>void}){
 const d=s.days[s.lastDay],missions=d.missions.map(id=>s.tasks.find(t=>t.id===id)),goal=s.rewards.find(r=>r.goal),done=d.missions.filter(id=>d.done.includes(id)).length,inbox=inboxCount(s);const icons=[Target,Zap,Sprout],labels=['MISIÓN PRINCIPAL','MISIÓN RÁPIDA','MISIÓN DE PROGRESO'];
 const mission=(i:number)=>{const t=missions[i],Icon=icons[i];return <article key={i} className={i===0?'mission primary':'card small-mission'}><div className="mission-top"><div className="eyebrow"><Icon size={17}/>{labels[i]}</div>{t&&!t.completed&&<button className="icon-button" title="Proponer otra misión" aria-label={'Cambiar '+labels[i].toLowerCase()} disabled={busy} onClick={()=>act({type:'replace',slot:i})}><RefreshCw size={15}/></button>}</div>{t?<><div className="area-label">{t.area}{t.projectId?' · '+s.projects.find(p=>p.id===t.projectId)?.name:''}</div><h2>{t.title}</h2><p className="next-action">{t.nextAction||t.steps[t.stepsDone]||'Empieza con el primer paso. Lo demás viene después.'}</p>{!t.completed&&<button className={'text-button assistant-task-link '+(i===0?'on-dark':'')} disabled={busy} onClick={()=>assist(t)}><Sparkles size={15}/>Ayúdame a empezar</button>}<div className="task-meta"><span><Clock size={14}/>{t.completed?`${t.actual} min reales`:`${t.estimated} min`}</span><span>{t.completed?`${t.points} pts obtenidos`:`+${nominal(t,t.estimated,false)} pts estimados`}</span></div>{t.completed?<div className="completed-label"><Check size={18}/>Misión completada</div>:<MissionExecution key={t.id} s={s} task={t} busy={busy} primary={i===0} start={start} open={open} complete={complete}/>}</>:<><h2>{i===0?'Define tu prioridad.':i===1?'Una acción breve.':'Un avance de fondo.'}</h2><p>{i===0?'Captura tus pendientes y deja que Balthazar te proponga las siguientes tres acciones.':i===1?'Una tarea de diez minutos o menos para ponerte en movimiento.':'Un avance importante, aunque no sea urgente.'}</p>{i===0&&<button className="button light" onClick={capture}><Plus size={17}/>Capturar mi primera tarea</button>}</>}{i===0&&<div className="orbit"><Compass/></div>}</article>};
 return <><div className="energy-bar"><span>ENERGÍA DISPONIBLE</span><div className="segmented">{(['alta','media','baja'] as const).map((e,i)=><button disabled={busy} key={e} aria-pressed={s.profile.energy===e} className={s.profile.energy===e?'selected':''} onClick={()=>act({type:'energy',value:e})}><span className={'energy-icon energy-'+i}>{'▮'.repeat(3-i)}</span>{e[0].toUpperCase()+e.slice(1)}</button>)}</div><span className="energy-note">Ajusta las misiones a cómo te sientes.</span></div><div className="workspace"><section><div className="section-title"><h2>Misiones de hoy</h2><button className="text-button" disabled={busy} onClick={()=>act({type:'plan'})}><RefreshCw size={15}/>Preparar misiones</button></div>{mission(0)}<div className="small-missions">{mission(1)}{mission(2)}</div>{inbox>0&&<button className="inbox-banner" disabled={busy} onClick={()=>act({type:'plan'})}><Inbox size={19}/><span><strong>{inbox} {inbox===1?'idea espera':'ideas esperan'} en tu Inbox.</strong> Organízalas y prepara tus misiones.</span><span>Preparar</span></button>}<div className="rescue-bar"><div><LifeBuoy size={22}/><div><strong>¿Necesitas ayuda para empezar?</strong><p>Puedo proponerte una acción y un arranque de cinco minutos.</p></div></div><button className="button secondary" onClick={rescue}>Estoy bloqueado</button></div></section><aside><article className="card daily-goal"><div className="eyebrow">PROGRESO DIARIO</div><div className="progress-number">{done}<span> / 3 misiones</span></div><div className="progress"><i style={{width:(done/3*100)+'%'}}/></div><div className={'victory '+(d.win?'won':'')}><Flame size={18}/>{d.win?'Victoria diaria conseguida':'Cada misión es un avance'}</div><p className="small">Completa la principal o dos tareas para conseguir tu victoria diaria.</p><div className="protocol-label">DESAFÍOS DIARIOS</div><DailyProtocol s={s}/><div className="bonus">{d.bonus?'Bonus conseguido':'Los tres desafíos'} <strong>+50 pts · +50 XP</strong></div></article><article className="card reward-teaser"><div className="eyebrow"><Gift size={16}/>RECOMPENSA OBJETIVO</div>{goal?<><div className="reward-emoji">{goal.emoji}</div><h3>{goal.name}</h3><div className="progress"><i style={{width:Math.min(100,s.points/goal.cost*100)+'%'}}/></div><p><strong>{s.points.toLocaleString('es-CO')}</strong> / {goal.cost.toLocaleString('es-CO')} pts</p></>:<><h3>Define una recompensa.</h3><p>Selecciona una meta en Recompensas para seguir su progreso aquí.</p></>}</article><div className="shield-note"><Shield size={17}/>{s.shields} {s.shields===1?'escudo disponible':'escudos disponibles'}<span>Cada 14 victorias ganas uno.</span></div><button className="text-button close-day" onClick={closeDay}><Moon size={17}/>Cerrar mi día</button></aside></div></>
}
