'use client';
import {useState} from 'react';
import {Mic,MicOff,PhoneOff,Volume2,Radio,Check,Trash2} from 'lucide-react';
import type {State} from '../lib/domain';
import type {Act} from './useQuest';
import Dialog from './Dialog';
import {useVoice} from './useVoice';
import {useWakeWord} from './useWakeWord';
export default function VoiceDialog({s,revision,refresh,act,busy,error,close}:{s:State;revision:number;refresh:()=>Promise<void>;act:Act;busy:boolean;error:string;close:()=>void}){
 const [consent,setConsent]=useState(false),[saved,setSaved]=useState(false);const v=useVoice(s,revision,refresh);
 const wake=useWakeWord(()=>{if(consent)void v.start()});
 const connected=v.status!=='Desconectado',draft=v.draft,stale=!!draft&&draft.revision!==revision;
 const begin=()=>{wake.stop();setSaved(false);void v.start()};
 async function apply(){if(!draft)return;wake.stop();v.end();const command=draft.kind==='day'?{type:'assistDay',taskIds:draft.items.map(i=>i.taskId)}:{type:'capture',tasks:draft.tasks.map(t=>({...t,...(draft.kind==='subtasks'?{parentId:draft.parentId}:{})}))};if(await act(command,draft.revision)){v.setDraft(null);setSaved(true)}}
 return <Dialog title="Hablar con Balthazar" close={()=>{wake.stop();v.end();close()}}>
  <p className="muted">Cuéntame cómo viene tu día. Podemos ordenar prioridades, capturar pendientes o dividir una misión.</p>
  <div className={'voice-console '+(connected?'voice-active':'')} role="status"><Radio size={30}/><strong>{wake.listening?'Esperando «Hola Balta»':v.status}</strong><span className="small">{connected?'Sesión de hasta 5 minutos':wake.listening?'Micrófono activo · detección local':'Voz generada por IA · español'}</span></div>
  {!connected&&<label className="assistant-consent"><input type="checkbox" checked={consent} disabled={wake.listening} onChange={e=>setConsent(e.target.checked)}/>Permito enviar mi voz, mis misiones disponibles y sus proyectos a OpenAI durante esta conversación.</label>}
  <div className="voice-controls">{!connected?<button className="button" disabled={!consent||busy} onClick={begin}><Mic size={18}/>Hablar con Balthazar</button>:<><button className="button secondary" disabled={v.status==='Conectando'} onClick={v.toggleMute}>{v.muted?<MicOff size={18}/>:<Mic size={18}/>} {v.muted?'Activar micrófono':'Silenciar'}</button><button className="button secondary" onClick={v.end}><PhoneOff size={18}/>Terminar</button><button className="text-button" onClick={v.resumeAudio}><Volume2 size={17}/>Escuchar respuesta</button></>}</div>
  {!connected&&<section className="voice-wake"><strong>Activación «Hola Balta»</strong><p className="small muted">Funciona con este panel abierto y visible. La detección es local; OpenAI se conecta cuando dices la frase. Apágala cuando no la necesites.</p>{wake.availability==='available'?<button className="button secondary" disabled={!consent||busy} onClick={()=>{if(wake.listening)wake.stop();else void wake.start()}}>{wake.listening?'Apagar escucha':'Escuchar «Hola Balta»'}</button>:['downloadable','downloading'].includes(wake.availability)?<button className="button secondary" disabled={wake.preparing} onClick={()=>{void wake.prepare()}}>{wake.preparing?'Preparando…':'Preparar voz local en este navegador'}</button>:<p className="small muted">{wake.availability==='checking'?'Comprobando voz local…':'Este navegador no ofrece reconocimiento local en español. Puedes conversar usando el botón.'}</p>}{wake.message&&<p className="small" role="status">{wake.message}</p>}</section>}
  {(v.error||error)&&<p className="error-inline" role="alert">{v.error||error}</p>}
  {v.lines.length>0&&<section className="voice-transcript" aria-label="Conversación actual">{v.lines.map(line=><p key={line.id}><strong>{line.who}</strong> {line.text}</p>)}</section>}
  {draft&&<section className="voice-draft"><h3>{draft.kind==='day'?'Plan propuesto':draft.kind==='subtasks'?'Subtareas propuestas':'Misiones propuestas'}</h3><p>{draft.summary}</p>{draft.kind==='subtasks'&&<p className="small muted">Para: {s.tasks.find(t=>t.id===draft.parentId)?.title}. Los pasos y el avance actuales se conservan.</p>}
   {draft.kind==='day'?draft.items.map(item=><article className="assistant-day-item" key={item.taskId}><strong>{s.tasks.find(t=>t.id===item.taskId)?.title||'Misión no disponible'}</strong><p>{item.minutes} min · {item.reason}</p><button className="text-button" onClick={()=>v.setDraft({...draft,items:draft.items.filter(x=>x.taskId!==item.taskId)})}>Quitar del plan</button></article>):draft.tasks.map((task,i)=><article className="assistant-draft" key={i}><div className="spread"><strong className="eyebrow">{draft.kind==='subtasks'?'SUBTAREA':'MISIÓN'}</strong><button className="icon-button" aria-label={'Quitar propuesta '+(i+1)} onClick={()=>v.setDraft({...draft,tasks:draft.tasks.filter((_,j)=>i!==j)})}><Trash2 size={16}/></button></div><label>Título<input maxLength={160} value={task.title} onChange={e=>v.setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,title:e.target.value}:t)})}/></label><label>Minutos estimados<input type="number" min={1} max={480} value={task.minutes} onChange={e=>v.setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,minutes:Number(e.target.value)}:t)})}/></label>{draft.kind==='capture'&&<div className="form-grid"><label>Área<select value={task.area} onChange={e=>v.setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,area:e.target.value,projectId:''}:t)})}>{s.areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Proyecto<select value={task.projectId} onChange={e=>{const project=s.projects.find(p=>p.id===e.target.value);v.setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,projectId:e.target.value,area:project?.area||t.area}:t)})}}><option value="">Sin proyecto</option>{s.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>}<label>Siguiente acción<input maxLength={300} value={task.nextAction} onChange={e=>v.setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,nextAction:e.target.value}:t)})}/></label></article>)}
   {stale&&<p className="hint">Tu espacio cambió. Inicia otra conversación antes de aplicar esta propuesta.</p>}
   <button className="button full" disabled={busy||stale||(draft.kind==='day'?!draft.items.length:!draft.tasks.length||draft.tasks.some(t=>!t.title.trim()||!t.nextAction.trim()||!Number.isInteger(t.minutes)||t.minutes<1||t.minutes>480))} onClick={()=>{void apply()}}><Check size={17}/>{draft.kind==='day'?'Aplicar plan a Hoy':'Guardar propuestas'}</button><p className="small muted">Al aplicar, termina la conversación y se guardan solo estas propuestas. No se completan misiones ni se conceden puntos.</p>
  </section>}
  {saved&&<p className="hint" role="status">Propuesta guardada. Ya puedes verla en tus misiones o en Hoy.</p>}
  <p className="assistant-footnote">No guardamos esta conversación ni el audio en Balthazar. Cada sesión usa tu espacio actual. La escucha y la conversación se detienen al ocultar la aplicación. Una sesión y cada propuesta consumen una consulta del límite diario compartido.</p>
 </Dialog>
}
