import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,apply} from '../app/lib/domain.ts';
import {buildContext,validateProposal} from '../lib/assistant.ts';

function setup(){return apply(fresh(),{id:'one',type:'capture',tasks:[{title:'Propuesta',area:'Trabajo',minutes:50,nextAction:'Abrir documento'},{title:'Dependiente',dependency:''}]})}
test('capture preserves explicit ISO deadline and rejects invented dates',()=>{const s=setup(),request={kind:'capture',text:'Entregar propuesta el 2026-10-08',revision:0,consent:true};const proposal={summary:'Propuesta',questions:[],tasks:[{title:'Entregar propuesta',area:'Trabajo',projectId:'',minutes:30,nextAction:'Revisar propuesta',due:'2026-10-08'}]};assert.equal(validateProposal(s,request,proposal).tasks[0].due,'2026-10-08');assert.throws(()=>validateProposal(s,{...request,text:'Entregar propuesta pronto'},proposal));assert.throws(()=>validateProposal(s,{...request,text:'Entrega el 2026-02-30'},{...proposal,tasks:[{...proposal.tasks[0],due:'2026-02-30'}]}))});
test('context excludes identity, economy, history and unrelated task descriptions',()=>{const s=setup();s.profile.name='PRIVATE_NAME';s.tasks[1].description='PRIVATE_OTHER';const context=JSON.stringify(buildContext(s,{kind:'task',taskId:s.tasks[0].id,text:'Me cuesta',revision:0,consent:true}));assert.ok(!context.includes('PRIVATE_NAME'));assert.ok(!context.includes('PRIVATE_OTHER'));assert.ok(!context.includes('rewards'));assert.ok(!context.includes('points'));assert.ok(context.includes('Propuesta'))});
test('capture proposals require known areas/projects and bounded drafts',()=>{const s=setup();const request={kind:'capture',text:'Leer',revision:0,consent:true};assert.throws(()=>validateProposal(s,request,{summary:'Listo',questions:[],tasks:[{title:'Leer',area:'INVENTADA',projectId:'',minutes:15,nextAction:'Abrir libro'}]}));assert.throws(()=>validateProposal(s,request,{summary:'Listo',questions:[],tasks:[{title:'Leer',area:'Trabajo',projectId:'inventado',minutes:15,nextAction:'Abrir libro'}]}))});
test('day advice rejects invented or blocked IDs and overcommitted blocks',()=>{const s=setup();const request={kind:'day',minutes:20,energy:'baja',revision:0,consent:true};assert.throws(()=>validateProposal(s,request,{summary:'Plan',questions:[],items:[{taskId:'invented',minutes:15,reason:'Urgente'}]}));assert.throws(()=>validateProposal(s,request,{summary:'Plan',questions:[],items:[{taskId:s.tasks[0].id,minutes:30,reason:'Avance'}]}));const result=validateProposal(s,request,{summary:'Plan',questions:[],items:[{taskId:s.tasks[0].id,minutes:15,reason:'Avance parcial'}]});assert.equal(result.items[0].minutes,15);s.tasks[0].status='BLOQUEADA';assert.throws(()=>validateProposal(s,request,result))});
test('assistant steps cannot overwrite advanced progress or completed tasks',()=>{let s=setup();const t=s.tasks[0];s=apply(s,{id:'steps',type:'assistSteps',taskId:t.id,nextAction:'Escribir título',steps:['Escribir título']});assert.equal(s.points,0);assert.equal(s.tasks[0].steps[0],'Escribir título');s.tasks[0].stepsDone=1;assert.throws(()=>apply(s,{id:'again',type:'assistSteps',taskId:t.id,nextAction:'Borrar',steps:['Borrar']}));s.tasks[0].stepsDone=0;s.tasks[0].completed=Date.now();assert.throws(()=>apply(s,{id:'completed',type:'assistSteps',taskId:t.id,nextAction:'Borrar',steps:['Borrar']}))});
