import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,apply} from '../app/lib/domain.ts';import {createBackup,parseBackup} from '../lib/backup.ts';import {createRepository} from '../lib/state-repository.ts';
test('purpose relations and activity roundtrip in backup',()=>{let s=apply(fresh(),{id:'p',type:'purpose',title:'Aprender',area:'Personal'});s=apply(s,{id:'project',type:'project',name:'Curso',area:'Personal'});s=apply(s,{id:'link',type:'linkPurpose',projectId:s.projects[0].id,purposeId:s.purposes[0].id});s=apply(s,{id:'balta',type:'baltaAction',source:'text',summary:'Captura',command:{type:'capture',tasks:[{title:'Estudiar'}]}});const restored=parseBackup(createBackup(s));assert.deepEqual(restored.purposes,s.purposes);assert.equal(restored.projects[0].purposeId,s.purposes[0].id);assert.deepEqual(restored.activity,s.activity)});
test('old backups normalize missing new fields without changing original',()=>{const s=fresh();delete s.purposes;delete s.activity;const backup=createBackup(s);const restored=parseBackup(backup);assert.deepEqual(restored.purposes,[]);assert.deepEqual(restored.activity,[]);assert.equal(s.purposes,undefined)});
test('backup rejects foreign purpose references',()=>{const backup=createBackup(fresh());backup.state.projects.push({id:'p',name:'Proyecto',area:'Personal',description:'',purposeId:'foreign'});assert.throws(()=>parseBackup(backup))});
test('restore cannot overwrite a space with purposes',async()=>{const s=apply(fresh(),{id:'purpose',type:'purpose',title:'Meta',area:'Personal'});const repo=createRepository({read:async()=>({state:s,revision:0}),insert:async()=>{},cas:async()=>{throw Error('MUST_NOT_WRITE')}});await assert.rejects(()=>repo.import('owner',0,createBackup(fresh())),/EMPTY_REQUIRED/)});
test('backup rejects forged plan receipt references',()=>{const backup=createBackup(fresh());backup.state.activity=[{id:'forged',source:'text',tool:'assistDay',at:Date.now(),status:'executed',summary:'Plan',receipt:{kind:'assistDay',day:backup.state.lastDay,before:['missing'],after:[],tasks:[]}}];assert.throws(()=>parseBackup(backup))});
test('purpose backup accepts empty date and rejects impossible date',()=>{const s=apply(fresh(),{id:'p',type:'purpose',title:'Aprender',area:'Personal'});const backup=createBackup(s);assert.equal(parseBackup(backup).purposes[0].due,'');backup.state.purposes[0].due='2026-02-30';assert.throws(()=>parseBackup(backup))});
test('retained receipt deduplicates old request even after applied ID eviction',async()=>{let s=apply(fresh(),{id:'original',type:'baltaAction',source:'text',summary:'Captura',command:{type:'capture',tasks:[{title:'Estudiar'}]}});s.applied=[];let writes=0;const repo=createRepository({read:async()=>({state:s,revision:250}),insert:async()=>{},cas:async()=>{writes++;return true}});const result=await repo.mutate('owner',0,{id:'original',type:'baltaAction',source:'text',summary:'Captura',command:{type:'capture',tasks:[{title:'Duplicar'}]}});assert.equal(result.state.tasks.length,1);assert.equal(writes,0)});
