import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,apply,nominal,dayKey,level,plan} from '../app/lib/domain.ts';
const now=Date.parse('2026-09-29T17:00:00Z');
const act=(s,a,t=now)=>apply(s,{id:crypto.randomUUID(),...a},t);
const create=(s,title='Leer artículo',extra={})=>act(s,{type:'capture',tasks:[{title,...extra}]});
test('reward bands and cap',()=>{for(const [m,v] of [[10,10],[11,20],[25,20],[26,40],[45,40],[46,70],[90,70],[91,100]])assert.equal(nominal({importance:1,difficulty:1,resistance:1},m,false),v);assert.equal(nominal({importance:5,difficulty:5,resistance:5},120,true),150)});
test('levels match spec',()=>{assert.equal(level(499),1);assert.equal(level(500),2);assert.equal(level(1100),3);assert.equal(level(1800),4)});
test('completion once and daily partial cap',()=>{let s=create(fresh(now),'Leer', {importance:1});s.points=285;s.days[s.lastDay].ordinary=285;const id=s.tasks[0].id;s=act(s,{type:'complete',taskId:id,minutes:30});assert.equal(s.points,300);assert.equal(s.xp,40);const again=act(s,{type:'complete',taskId:id,minutes:30});assert.equal(again.points,300);assert.equal(again.xp,40)});
test('redemption atomic and XP unchanged; replay idempotent',()=>{let s=fresh(now);s.points=500;s.xp=600;const a={id:'redeem-1',type:'redeem',rewardId:s.rewards[0].id};s=apply(s,a,now);assert.equal(s.points,200);assert.equal(s.xp,600);assert.equal(apply(s,a,now).points,200);assert.throws(()=>act(s,{type:'redeem',rewardId:s.rewards[0].id}),/puntos/);assert.equal(s.redemptions.length,1)});
test('arranque gives focus XP only and persists pause time',()=>{let s=create(fresh(now));s=act(s,{type:'start',taskId:s.tasks[0].id,kind:'kickstart'});s=act(s,{type:'pause'},now+120000);s=act(s,{type:'resume'},now+240000);s=act(s,{type:'finishFocus'},now+420000);assert.equal(s.xp,5);assert.equal(s.points,0);assert.notEqual(s.tasks[0].status,'COMPLETADA');assert.equal(s.days[s.lastDay].focusMinutes,5);assert.equal(s.days[s.lastDay].focus,false)});
test('one active session, not two',()=>{let s=create(fresh(now));s=act(s,{type:'start',taskId:s.tasks[0].id});assert.throws(()=>act(s,{type:'start',taskId:s.tasks[0].id}),/sesión/)});
test('distinct balanced missions',()=>{let s=fresh(now);s=create(s,'Revisar contrato',{minutes:50,importance:5});s=create(s,'Enviar correo',{minutes:8});s=create(s,'Leer artículo',{minutes:30,importance:4});s=act(s,{type:'plan'});assert.equal(new Set(s.days[s.lastDay].missions).size,3);assert.equal(s.tasks.find(t=>t.id===s.days[s.lastDay].missions[1]).estimated,8)});
test('principal victory and daily bonus awarded once',()=>{let s=fresh(now);s=create(s,'Concepto',{minutes:30,importance:5});s=create(s,'Correo',{minutes:8});s=act(s,{type:'plan'});const [main,quick]=s.days[s.lastDay].missions;s=act(s,{type:'start',taskId:main});s=act(s,{type:'complete',taskId:main,minutes:25},now+1500000);assert.equal(s.streak,1);s=act(s,{type:'complete',taskId:quick,minutes:8},now+1501000);assert.equal(s.days[s.lastDay].bonus,true);const p=s.points;s=act(s,{type:'complete',taskId:quick,minutes:8},now+1502000);assert.equal(s.points,p);assert.equal(s.streak,1)});
test('shields protect without inventing success',()=>{let s=fresh(now);s.streak=5;s.best=5;s.shields=1;s.days[s.lastDay].win=false;s=act(s,{type:'energy',value:'media'},now+86400000);assert.equal(s.streak,5);assert.equal(s.shields,0);s=act(s,{type:'energy',value:'media'},now+2*86400000);assert.equal(s.streak,0);assert.equal(s.best,5);assert.equal(s.xp,0)});
test('duplicate capture rejects atomically',()=>{let s=create(fresh(now),'Enviar correo');assert.throws(()=>create(s,'ENVIAR  CORREO'),/existe/);assert.equal(s.tasks.length,1)});
test('Bogota day uses local midnight',()=>{assert.equal(dayKey(Date.parse('2026-09-30T04:59:00Z'),'America/Bogota'),'2026-09-29')});


test('old redemption command cannot debit twice after dedupe window',()=>{let s=fresh(now);s.points=1000;const cmd={id:'permanent-redeem',type:'redeem',rewardId:'coffee'};s=apply(s,cmd,now);for(let i=0;i<201;i++)s=act(s,{type:'energy',value:'media'});s=apply(s,cmd,now);assert.equal(s.points,700);assert.equal(s.redemptions.length,1)});
test('expired session confirmed tomorrow belongs to yesterday',()=>{const late=Date.parse('2026-09-30T04:20:00Z');let s=create(fresh(late),'Correo',{minutes:5});s=act(s,{type:'complete',taskId:s.tasks[0].id,minutes:5},late);s=create(s,'Leer',{minutes:25});s=act(s,{type:'start',taskId:s.tasks[1].id},late);s=act(s,{type:'finishFocus'},Date.parse('2026-09-30T05:05:00Z'));assert.equal(s.days['2026-09-29'].focus,true);assert.equal(s.days['2026-09-29'].win,true);assert.equal(s.days['2026-09-30'].focusMinutes,0);assert.equal(s.streak,1)});
test('replan fills empty principal from remaining candidates',()=>{let s=fresh(now);for(const [title,minutes,importance] of [['Principal',40,5],['Breve',8,3],['Progreso',30,4],['Alternativa',25,3]])s=create(s,title,{minutes,importance});s=act(s,{type:'plan'});s=act(s,{type:'status',taskId:s.days[s.lastDay].missions[0],status:'CANCELADA'});s=act(s,{type:'plan'});assert.ok(s.days[s.lastDay].missions[0]);assert.equal(new Set(s.days[s.lastDay].missions).size,3)});
test('completion uses recorded actual duration when omitted',()=>{let s=create(fresh(now),'Leer',{minutes:25,importance:1});const id=s.tasks[0].id;s=act(s,{type:'start',taskId:id});s=act(s,{type:'finishFocus'},now+1500000);s=act(s,{type:'start',taskId:id},now+1500000);s=act(s,{type:'finishFocus'},now+3000000);s=act(s,{type:'complete',taskId:id},now+3000000);assert.equal(s.tasks[0].actual,50);assert.equal(s.tasks[0].points,80)});


test('renamed default area still allows quick capture and parking',()=>{let s=fresh(now);s=act(s,{type:'area',oldName:'Personal',name:'Vida'});s=create(s,'Llamar a Paula');assert.ok(s.areas.includes(s.tasks[0].area))});
test('new day automatically proposes existing planned tasks',()=>{let s=create(fresh(now));s=act(s,{type:'plan'});s=act(s,{type:'energy',value:'media'},now+86400000);assert.ok(s.days[s.lastDay].missions[0])});
test('Daily Set bonus can exceed ordinary cap only once',()=>{let s=fresh(now);s=create(s,'Prioridad',{minutes:25,importance:5});s=create(s,'Breve',{minutes:8});s=act(s,{type:'plan'});const [main,quick]=s.days[s.lastDay].missions;s.points=300;s.days[s.lastDay].ordinary=300;s=act(s,{type:'start',taskId:main});s=act(s,{type:'complete',taskId:main,minutes:25},now+1500000);s=act(s,{type:'complete',taskId:quick,minutes:8},now+1501000);assert.equal(s.points,350);assert.equal(s.days[s.lastDay].ordinary,300);assert.equal(s.days[s.lastDay].bonus,true)});
test('dependency cycles are rejected',()=>{let s=create(fresh(now),'A');s=create(s,'B');const [a,b]=s.tasks;s=act(s,{type:'editTask',taskId:a.id,title:'A',dependency:b.id});assert.throws(()=>act(s,{type:'editTask',taskId:b.id,title:'B',dependency:a.id}),/ciclo/)});


test('completion accepts effort accumulated across several workdays',()=>{let s=create(fresh(now),'Preparar proyecto largo');const id=s.tasks[0].id;s=act(s,{type:'complete',taskId:id,minutes:900});assert.equal(s.tasks[0].actual,900);assert.ok(s.tasks[0].points<=150)});
