import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,apply} from '../app/lib/domain.ts';
import {execution,inboxCount,rescueTask} from '../lib/execution.ts';
function seed(){let s=apply(fresh(),{id:'seed',type:'capture',tasks:[{title:'Principal'},{title:'Acción uno'},{title:'Acción dos'}]});for(const t of s.tasks.slice(1))s=apply(s,{id:t.id,type:'reparent',taskId:t.id,parentId:s.tasks[0].id});return s;}
test('inbox counts main tasks and daily execution offers children only',()=>{const s=seed();assert.equal(inboxCount(s),1);const e=execution(s,s.tasks[0]);assert.deepEqual(e.options.map(t=>t.title),['Acción uno','Acción dos']);assert.equal(e.ready,false);assert.equal(e.done,0);assert.ok(rescueTask(s).parentId)});
test('unavailable parents and their dependencies never offer a rescue',()=>{for(const status of ['ARCHIVADA','BLOQUEADA','CANCELADA']){const s=seed();s.tasks[0].status=status;assert.equal(execution(s,s.tasks[0]).options.length,0);assert.equal(rescueTask(s),undefined)}const s=seed();s.tasks.push({...s.tasks[0],id:'dependency',title:'Dependencia',parentId:undefined});s.tasks[0].dependency='dependency';assert.equal(execution(s,s.tasks[0]).options.length,0);assert.equal(rescueTask(s).id,'dependency')});
test('completed children lead to result review without another automatic session',()=>{let s=seed();for(const t of s.tasks.slice(1))s=apply(s,{id:'done'+t.id,type:'complete',taskId:t.id});const e=execution(s,s.tasks[0]);assert.equal(e.ready,true);assert.equal(e.done,2);assert.equal(e.options.length,0);assert.equal(rescueTask(s),undefined);assert.equal(s.points,0);assert.equal(s.focus,null)});
test('blocked children are omitted and unfinished principal steps remain actionable',()=>{const s=seed();s.tasks[1].status='BLOQUEADA';assert.deepEqual(execution(s,s.tasks[0]).options.map(t=>t.id),[s.tasks[2].id]);s.tasks[0].steps=['Revisar resultado'];assert.equal(execution(s,s.tasks[0]).options[0].id,s.tasks[0].id);s.tasks[0].completed=Date.now();assert.equal(execution(s,s.tasks[0]).ready,false);assert.equal(execution(s,s.tasks[0]).options.length,0)});
test('rescue never suggests a second session while paused focus remains open',()=>{let s=seed();s=apply(s,{id:'start',type:'start',taskId:s.tasks[1].id});s=apply(s,{id:'pause',type:'pause'});assert.equal(rescueTask(s),undefined);});
