import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh} from '../app/lib/domain.ts';
import {createRepository} from '../lib/state-repository.ts';
import {createBackup,parseBackup} from '../lib/backup.ts';
import {allowedEmail,isSameOrigin} from '../lib/access.ts';

function memory(){const rows=new Map();return {read:async id=>structuredClone(rows.get(id)||null),insert:async(id,state)=>{if(!rows.has(id))rows.set(id,{state:structuredClone(state),revision:0})},cas:async(id,revision,state)=>{if(rows.get(id)?.revision!==revision)return false;rows.set(id,{state:structuredClone(state),revision:revision+1});return true}}}
test('concurrent commands preserve one winner and reject stale revision',async()=>{const repo=createRepository(memory());await repo.read('a');const results=await Promise.allSettled([repo.mutate('a',0,{id:'one',type:'energy',value:'alta'}),repo.mutate('a',0,{id:'two',type:'energy',value:'baja'})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.find(x=>x.status==='rejected').reason.message,'CONFLICT')});
test('retried capture is idempotent and users stay isolated',async()=>{const repo=createRepository(memory());const command={id:'retry',type:'capture',tasks:[{title:'Preparar migración'}]};await repo.read('a');await repo.mutate('a',0,command);const replay=await repo.mutate('a',0,command);assert.equal(replay.state.tasks.length,1);assert.equal(replay.revision,1);assert.equal((await repo.read('b')).state.tasks.length,0)});
test('backup roundtrip preserves balances and pauses running timer',()=>{const state=fresh();state.points=123;state.focus={taskId:'t',started:Date.now()-5000,seconds:0,target:1500,kind:'normal'};state.tasks.push({id:'t',title:'Leer',description:'',area:'Personal',projectId:'',status:'EN_CURSO',created:Date.now(),due:'',estimated:25,actual:0,importance:3,difficulty:3,resistance:3,energy:'media',nextAction:'',steps:[],stepsDone:0,points:0,xp:0,dependency:''});const backup=createBackup(state);const restored=parseBackup(JSON.parse(JSON.stringify(backup)));assert.equal(restored.points,123);assert.equal(restored.focus.started,null);assert.ok(restored.focus.seconds>=5);assert.equal(state.focus.started===null,false)});
test('backup rejects unknown version, negative balance and broken references',()=>{const backup=createBackup(fresh());assert.throws(()=>parseBackup({...backup,version:99}));assert.throws(()=>parseBackup({...backup,state:{...backup.state,points:-1}}));assert.throws(()=>parseBackup({...backup,state:{...backup.state,focus:{taskId:'missing',started:null,seconds:0,target:1500,kind:'normal'}}}))});
test('import cannot overwrite existing progress and imported commands do not replay',async()=>{const repo=createRepository(memory());await repo.read('a');await repo.mutate('a',0,{id:'captured',type:'capture',tasks:[{title:'Existente'}]});await assert.rejects(repo.import('a',1,createBackup(fresh())),/EMPTY_REQUIRED/);const restored=await repo.import('b',0,createBackup(fresh()));assert.equal(restored.revision,1)});
test('access fails closed and cross-origin writes are refused',()=>{assert.equal(allowedEmail('Jorge@EXAMPLE.com','jorge@example.com'),true);assert.equal(allowedEmail('other@example.com','jorge@example.com'),false);assert.equal(allowedEmail('jorge@example.com',''),false);assert.equal(isSameOrigin(new Request('https://balthazar.example/api',{headers:{origin:'https://evil.example'}})),false);assert.equal(isSameOrigin(new Request('https://balthazar.example/api',{headers:{origin:'https://balthazar.example'}})),true)});
