import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createSupportHandlers} from '../lib/support-handlers.ts';
import {MAX_SUPPORT_BYTES} from '../lib/supports.ts';
const fileId='12345678-1234-1234-1234-123456789abc_a.pdf';
const origin='https://example.test';
function setup({tasks=['task'],counts=[0,1],authenticated=true}={}){
 const calls=[];let countIndex=0;
 const bucket={list:async(folder)=>{calls.push(['list',folder]);return {data:Array.from({length:counts[Math.min(countIndex++,counts.length-1)]},(_,i)=>({id:String(i),name:fileId,metadata:{size:3},created_at:'2026-10-04'})),error:null}},download:async(path)=>{calls.push(['download',path]);return {data:new Blob(['private bytes']),error:null}},upload:async(path,file,options)=>{calls.push(['upload',path,file.size,options]);return {error:null}},remove:async(paths)=>{calls.push(['remove',paths]);return {error:null}}};
 const client={storage:{from:(name)=>{calls.push(['bucket',name]);return bucket}}};
 const handlers=createSupportHandlers({authenticate:async()=>authenticated?{client,user:{id:'owner'}}:null,read:async(_client,owner)=>{calls.push(['read',owner]);return {state:{tasks:tasks.map(id=>({id}))}}}});
 return {handlers,calls};
}
function upload(name='a.pdf',type='application/pdf'){const form=new FormData();form.set('task','task');form.set('file',new File(['pdf'],name,{type}));return new Request(origin+'/api/supports',{method:'POST',headers:{origin},body:form});}
test('auth and origin failures do not touch Storage',async()=>{const {handlers,calls}=setup({authenticated:false});assert.equal((await handlers.GET(new Request(origin+'/api/supports?task=task'))).status,401);assert.equal((await handlers.POST(upload())).status,401);assert.equal((await handlers.DELETE(new Request(origin+'/api/supports?task=task&file='+fileId,{method:'DELETE',headers:{origin:'https://foreign.test'}}))).status,403);assert.equal(calls.length,0)});
test('missing or traversal task cannot reach Storage',async()=>{const {handlers,calls}=setup();for(const task of ['missing','../task','owner/task']){const res=await handlers.GET(new Request(origin+'/api/supports?task='+encodeURIComponent(task)));assert.ok([400,404].includes(res.status))}assert.ok(!calls.some(c=>c[0]==='bucket'))});
test('list always uses session owner and exact task folder',async()=>{const {handlers,calls}=setup();const res=await handlers.GET(new Request(origin+'/api/supports?task=task&owner=foreign'));assert.equal(res.status,200);assert.deepEqual(calls,[['read','owner'],['bucket','balthazar-supports'],['list','owner/task']]);assert.equal(res.headers.get('cache-control'),'private, no-store')});
test('authenticated download streams attachment without caching',async()=>{const {handlers,calls}=setup();const res=await handlers.GET(new Request(origin+'/api/supports?task=task&file='+fileId));assert.equal(res.status,200);assert.ok(res.body instanceof ReadableStream);assert.equal(await res.text(),'private bytes');assert.equal(res.headers.get('cache-control'),'private, no-store');assert.equal(res.headers.get('content-type'),'application/octet-stream');assert.match(res.headers.get('content-disposition'),/^attachment; filename="a.pdf";/);assert.deepEqual(calls.at(-1),['download','owner/task/'+fileId]);const bad=await handlers.GET(new Request(origin+'/api/supports?task=task&file='+encodeURIComponent('foreign/task/'+fileId)));assert.equal(bad.status,400);assert.equal(calls.filter(c=>c[0]==='download').length,1)});
test('valid upload stores opaque safe filename without overwrite',async()=>{const {handlers,calls}=setup();const res=await handlers.POST(upload('../a.pdf'));assert.equal(res.status,201);const data=await res.json(),call=calls.find(c=>c[0]==='upload');assert.match(data.file.id,/^[0-9a-f-]{36}__a.pdf$/);assert.equal(call[1],'owner/task/'+data.file.id);assert.deepEqual(call[3],{contentType:'application/pdf',upsert:false});assert.equal(calls.filter(c=>c[0]==='read').length,2)});
test('stream bound rejects missing Content-Length and cancels body',async()=>{let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(MAX_SUPPORT_BYTES+65537))},cancel(){cancelled=true}});const {handlers,calls}=setup();const request=new Request(origin+'/api/supports',{method:'POST',headers:{origin,'content-type':'multipart/form-data; boundary=a'},body:stream,duplex:'half'});const res=await handlers.POST(request);assert.equal(res.status,413);assert.equal(cancelled,true);assert.equal(calls.length,0)});
test('twenty cap rejects before upload and compensates concurrent overflow',async()=>{let fixture=setup({counts:[20]});assert.equal((await fixture.handlers.POST(upload())).status,400);assert.ok(!fixture.calls.some(c=>c[0]==='upload'));fixture=setup({counts:[19,21]});assert.equal((await fixture.handlers.POST(upload())).status,400);const uploaded=fixture.calls.find(c=>c[0]==='upload');assert.deepEqual(fixture.calls.at(-1),['remove',[uploaded[1]]])});
test('delete cannot address foreign folder',async()=>{const {handlers,calls}=setup();const request=file=>new Request(origin+'/api/supports?task=task&file='+encodeURIComponent(file),{method:'DELETE',headers:{origin}});assert.equal((await handlers.DELETE(request('../'+fileId))).status,400);assert.ok(!calls.some(c=>c[0]==='remove'));assert.equal((await handlers.DELETE(request(fileId))).status,200);assert.deepEqual(calls.at(-1),['remove',['owner/task/'+fileId]])});
