import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,apply} from '../app/lib/domain.ts';
import {wakePhrase,voiceContext} from '../lib/voice.ts';

test('wake phrase accepts greeting variations but not unrelated ambient speech',()=>{for(const text of ['Hola Balta','¡Hola, Balta!','hola balthazar organiza mi día'])assert.equal(wakePhrase(text),true);for(const text of ['Balta','hablé con Balta','hola Baltasarito','hola Paula'])assert.equal(wakePhrase(text),false)});
test('voice context includes current task relations without identity, supports or economy',()=>{const s=apply(fresh(),{id:'capture',type:'capture',tasks:[{title:'Clase'}]});s.tasks[0].description='PRIVATE_DOCUMENT';s.tasks[0].supportLinks=[{id:'one',name:'PRIVATE_FILE',url:'https://private.test'}];s.profile.name='PRIVATE_PERSON';const c=voiceContext(s);assert.equal(c.tasks[0].title,'Clase');const text=JSON.stringify(c);for(const privateValue of ['PRIVATE_DOCUMENT','PRIVATE_FILE','PRIVATE_PERSON','rewards','points'])assert.ok(!text.includes(privateValue))});

test('reviewed daily plan preserves completed slots and grants no progress',()=>{let s=apply(fresh(),{id:'capture',type:'capture',tasks:[{title:'Una'},{title:'Dos'},{title:'Tres'}]});const [one,two,three]=s.tasks;s=apply(s,{id:'done',type:'complete',taskId:one.id,minutes:10});s.days[s.lastDay].missions=[one.id,two.id,''];const before={points:s.points,xp:s.xp};const next=apply(s,{id:'review',type:'assistDay',taskIds:[three.id]});assert.deepEqual(next.days[next.lastDay].missions,[one.id,three.id,'']);assert.equal(next.tasks[2].status,'HOY');assert.equal(next.points,before.points);assert.equal(next.xp,before.xp);assert.equal(s.tasks[2].status,'INBOX')});
test('daily plan rejects unavailable, duplicate, child and active-session selections',()=>{const s=apply(fresh(),{id:'capture',type:'capture',tasks:[{title:'Una'},{title:'Dos'}]});const one=s.tasks[0];for(const taskIds of [[one.id,one.id],['invented'],[]])assert.throws(()=>apply(s,{id:'bad',type:'assistDay',taskIds}));one.status='BLOQUEADA';assert.throws(()=>apply(s,{id:'blocked',type:'assistDay',taskIds:[one.id]}));one.status='INBOX';const child=apply(s,{id:'child',type:'capture',tasks:[{title:'Hija',parentId:one.id}]});assert.throws(()=>apply(child,{id:'child-plan',type:'assistDay',taskIds:[child.tasks[2].id]}));const active=apply(s,{id:'start',type:'start',taskId:one.id});assert.throws(()=>apply(active,{id:'active-plan',type:'assistDay',taskIds:[s.tasks[1].id]}))});
test('completed quick mission never becomes main or grants a victory after replanning',()=>{let s=apply(fresh(),{id:'capture',type:'capture',tasks:[{title:'Principal'},{title:'Rápida'},{title:'Nueva'}]});const [main,quick,next]=s.tasks;s.days[s.lastDay].missions=[main.id,quick.id,''];s=apply(s,{id:'done',type:'complete',taskId:quick.id,minutes:5});s=apply(s,{id:'review',type:'assistDay',taskIds:[next.id]});assert.deepEqual(s.days[s.lastDay].missions,[next.id,quick.id,'']);s=apply(s,{id:'start',type:'start',taskId:next.id});s=apply(s,{id:'finish',type:'finishFocus'});assert.equal(s.victories,0);assert.equal(s.days[s.lastDay].win,false)});
