import {authenticated} from '../../../lib/auth';
import {repository} from '../../../lib/repository';
import {createBackup} from '../../../lib/backup';
import {isSameOrigin} from '../../../lib/access';
import {BACKUP_SIZE_ERROR,readBackupRequest} from '../../../lib/backup-transfer';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(){try{const auth=await authenticated();if(!auth)return json({error:'Inicia sesión.'},401);const {state}=await repository(auth.client).read(auth.user.id);return new Response(JSON.stringify(createBackup(state),null,2),{headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','Content-Disposition':'attachment; filename="balthazar-backup-'+new Date().toISOString().slice(0,10)+'.json"'}})}catch{return json({error:'No se pudo exportar. Intenta de nuevo.'},503)}}
export async function POST(request:Request){if(!isSameOrigin(request))return json({error:'Solicitud no permitida.'},403);try{const auth=await authenticated();if(!auth)return json({error:'Inicia sesión.'},401);const raw=await readBackupRequest(request);const {revision,backup}=JSON.parse(raw);if(!Number.isInteger(revision)||revision<0)return json({error:'Revisión inválida.'},400);return json({...await repository(auth.client).import(auth.user.id,revision,backup),owner:auth.user.id})}catch(e){const message=e instanceof Error?e.message:'';if(message===BACKUP_SIZE_ERROR)return json({error:BACKUP_SIZE_ERROR},413);if(message==='CONFLICT')return json({error:'Tu progreso cambió; recarga antes de importar.'},409);if(message==='EMPTY_REQUIRED')return json({error:'Solo puedes importar en un espacio sin actividad. Tu progreso actual se conserva.'},409);return json({error:message==='STORAGE_UNAVAILABLE'?'No se pudo guardar. Intenta de nuevo.':message||'Respaldo inválido.'},400)}}
