import {routineSchema,routineEntrySchema,validateRoutineReferences} from './routines.ts';
import {validPurposeDate} from './purposes.ts';
import {activitySchema} from './activity.ts';
import {z} from 'zod';
import {elapsed,type State} from '../app/lib/domain.ts';
const n=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),t=(max=1000)=>z.string().max(max),id=t(160),ids=z.array(id).max(20000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v+'T12:00:00Z'))),energy=z.enum(['alta','media','baja']);
const task=z.object({supportVersion:n.optional(),parentId:id.optional(),supportLinks:z.array(z.object({id,name:t(160),url:t(2000).url().refine(v=>{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password})})).max(20).optional(),id,title:t(160),description:t(),area:t(80),projectId:id,status:z.enum(['INBOX','PLANIFICADA','HOY','EN_CURSO','PAUSADA','BLOQUEADA','COMPLETADA','CANCELADA','ARCHIVADA']),created:n,due:z.union([z.literal(''),date]),estimated:n.min(1).max(480),actual:n.max(10080),importance:n.min(1).max(5),difficulty:n.min(1).max(5),resistance:n.min(1).max(5),energy,nextAction:t(300),steps:z.array(t(300)).max(50),stepsDone:n.max(50),completed:n.optional(),points:n,xp:n,dependency:id});
const day=z.object({missions:z.array(id).max(3),done:ids,ordinary:n.max(300),xp:n,focusMinutes:n,focusXP:n.max(60),focus:z.boolean(),bonus:z.boolean(),win:z.boolean(),protected:z.boolean(),mood:t(80),tomorrow:t()});
const schema=z.object({routines:z.array(routineSchema).max(100).default([]),routineEntries:z.array(routineEntrySchema).max(36600).default([]),installedRoutinePacks:z.array(z.enum(['light-week','observe-three'])).max(2).default([]),installedRewardPacks:z.array(z.literal('personal-rewards')).max(1).default([]),activity:z.array(activitySchema).max(200).default([]),purposes:z.array(z.object({id:z.string().min(1).max(100),title:t(160).min(1),area:t(80),description:t(),due:z.string().refine(v=>{try{validPurposeDate(v);return true}catch{return false}}),status:z.enum(['active','archived'])})).max(100).default([]),profile:z.object({name:t(60),timezone:t(80).refine(tz=>{try{new Intl.DateTimeFormat('es',{timeZone:tz});return true}catch{return false}}),energy,onboarded:z.boolean()}),created:n,lastDay:date,xp:n,points:n,streak:n,best:n,shields:n.max(7),victories:n,areas:z.array(t(80)).max(100),tasks:z.array(task).max(20000),projects:z.array(z.object({purposeId:id.optional(),id,name:t(160),area:t(80),description:t()})).max(2000),rewards:z.array(z.object({id,name:t(160),cost:n.min(1),category:t(80),emoji:t(32),goal:z.boolean()})).max(2000),redemptions:z.array(z.object({id,name:t(160),cost:n,at:n})).max(20000),sessions:z.array(z.object({taskId:id,seconds:n,at:n,kind:t(30)})).max(50000),days:z.record(date,day),focus:z.object({taskId:id,started:z.union([z.null(),n]),seconds:n,target:n.min(1),kind:z.enum(['normal','kickstart'])}).nullable(),applied:ids});
export function createBackup(state:State,now=Date.now()){const copy=structuredClone(state);if(copy.focus){copy.focus.seconds=Math.floor(elapsed(copy.focus,now));copy.focus.started=null}return {format:'balthazar-backup',version:1,exportedAt:new Date(now).toISOString(),state:copy}}
export function parseBackup(value:unknown):State{
 const envelope=z.object({format:z.literal('balthazar-backup'),version:z.literal(1),exportedAt:z.string().datetime(),state:schema}).safeParse(value);
 if(!envelope.success)throw Error('Respaldo inválido o versión no compatible.');
 const s=envelope.data.state as State,taskIds=new Set(s.tasks.map(t=>t.id)),projects=new Set(s.projects.map(p=>p.id));
 if(taskIds.size!==s.tasks.length||projects.size!==s.projects.length||new Set(s.rewards.map(r=>r.id)).size!==s.rewards.length||new Set(s.redemptions.map(r=>r.id)).size!==s.redemptions.length)throw Error('El respaldo contiene identificadores duplicados.');
 validateRoutineReferences(s);const purposeIds=new Set(s.purposes!.map(p=>p.id));if(purposeIds.size!==s.purposes!.length||s.purposes!.some(p=>!s.areas.includes(p.area))||s.projects.some(p=>p.purposeId&&!purposeIds.has(p.purposeId))||new Set(s.activity!.map(a=>a.id)).size!==s.activity!.length)throw Error('El respaldo contiene propósitos o actividad inválidos.');
 const valid=(ref:string)=>!ref||taskIds.has(ref);
 for(const event of s.activity!){const r=event.receipt;if(r.kind==='capture'){if(new Set(r.tasks.map(t=>t.id)).size!==r.tasks.length||r.tasks.some(t=>!taskIds.has(t.id)||!s.areas.includes(t.area)||!valid(t.parentId||'')||!valid(t.dependency)||(t.projectId&&!projects.has(t.projectId))))throw Error('El respaldo contiene comprobantes inválidos.')}else if(r.kind==='assistDay'){const refs=[...r.before,...r.after].filter(Boolean);if(!s.days[r.day]||refs.some(id=>!taskIds.has(id))||r.tasks.some(t=>!taskIds.has(t.id))||new Set(r.tasks.map(t=>t.id)).size!==r.tasks.length||[r.before,r.after].some(ids=>new Set(ids.filter(Boolean)).size!==ids.filter(Boolean).length)||refs.some(id=>!r.tasks.some(t=>t.id===id)))throw Error('El respaldo contiene comprobantes inválidos.')}else if(!projects.has(r.projectId)||(r.before&&!purposeIds.has(r.before))||(r.after&&!purposeIds.has(r.after)))throw Error('El respaldo contiene comprobantes inválidos.')}
 if(!s.days[s.lastDay]||Object.keys(s.days).length>10000||s.lastDay<'2020-01-01'||s.lastDay>new Date().toISOString().slice(0,10)||s.tasks.some(t=>!valid(t.dependency)||t.dependency===t.id||(t.projectId&&!projects.has(t.projectId))||t.stepsDone>t.steps.length)||s.sessions.some(x=>!taskIds.has(x.taskId))||Object.values(s.days).some(d=>[...d.done,...d.missions].some(ref=>!valid(ref)))||(s.focus&&!taskIds.has(s.focus.taskId)))throw Error('El respaldo contiene referencias o fechas inválidas.');
 for(const task of s.tasks)if(task.parentId){const parent=s.tasks.find(t=>t.id===task.parentId);if(!parent||parent.id===task.id||parent.parentId||parent.area!==task.area||parent.projectId!==task.projectId)throw Error('El respaldo contiene subtareas inválidas.')}
 for(const parent of s.tasks){const children=new Set(s.tasks.filter(t=>t.parentId===parent.id).map(t=>t.id));const seen=new Set<string>();let ref=parent.dependency;while(ref&&!seen.has(ref)){if(children.has(ref))throw Error('El respaldo contiene una principal dependiente de su subtarea.');seen.add(ref);ref=s.tasks.find(t=>t.id===ref)?.dependency||''}}
 const visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string)=>{if(visiting.has(id))throw Error('El respaldo contiene ciclos de subtareas y dependencias.');if(visited.has(id))return;visiting.add(id);const t=s.tasks.find(t=>t.id===id)!;if(t.dependency)visit(t.dependency);for(const child of s.tasks.filter(x=>x.parentId===id))visit(child.id);visiting.delete(id);visited.add(id)};for(const task of s.tasks)visit(task.id);
 const dependencies=new Map(s.tasks.map(t=>[t.id,t.dependency]));for(const task of s.tasks){const seen=new Set<string>();let ref=task.id;while(ref){if(seen.has(ref))throw Error('El respaldo contiene dependencias circulares.');seen.add(ref);ref=dependencies.get(ref)||''}}
 if(s.focus){s.focus.seconds=Math.min(s.focus.seconds,s.focus.target);s.focus.started=null}return s;
}
