import {z} from 'zod';
import {elapsed,type State} from '../app/lib/domain.ts';
const n=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),t=(max=1000)=>z.string().max(max),id=t(160),ids=z.array(id).max(20000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v+'T12:00:00Z'))),energy=z.enum(['alta','media','baja']);
const task=z.object({id,title:t(160),description:t(),area:t(80),projectId:id,status:z.enum(['INBOX','PLANIFICADA','HOY','EN_CURSO','PAUSADA','BLOQUEADA','COMPLETADA','CANCELADA','ARCHIVADA']),created:n,due:z.union([z.literal(''),date]),estimated:n.min(1).max(480),actual:n.max(10080),importance:n.min(1).max(5),difficulty:n.min(1).max(5),resistance:n.min(1).max(5),energy,nextAction:t(300),steps:z.array(t(300)).max(50),stepsDone:n.max(50),completed:n.optional(),points:n,xp:n,dependency:id});
const day=z.object({missions:z.array(id).max(3),done:ids,ordinary:n.max(300),xp:n,focusMinutes:n,focusXP:n.max(60),focus:z.boolean(),bonus:z.boolean(),win:z.boolean(),protected:z.boolean(),mood:t(80),tomorrow:t()});
const schema=z.object({profile:z.object({name:t(60),timezone:t(80).refine(tz=>{try{new Intl.DateTimeFormat('es',{timeZone:tz});return true}catch{return false}}),energy,onboarded:z.boolean()}),created:n,lastDay:date,xp:n,points:n,streak:n,best:n,shields:n.max(7),victories:n,areas:z.array(t(80)).max(100),tasks:z.array(task).max(20000),projects:z.array(z.object({id,name:t(160),area:t(80),description:t()})).max(2000),rewards:z.array(z.object({id,name:t(160),cost:n.min(1),category:t(80),emoji:t(32),goal:z.boolean()})).max(2000),redemptions:z.array(z.object({id,name:t(160),cost:n,at:n})).max(20000),sessions:z.array(z.object({taskId:id,seconds:n,at:n,kind:t(30)})).max(50000),days:z.record(date,day),focus:z.object({taskId:id,started:z.union([z.null(),n]),seconds:n,target:n.min(1),kind:z.enum(['normal','kickstart'])}).nullable(),applied:ids});
export function createBackup(state:State,now=Date.now()){const copy=structuredClone(state);if(copy.focus){copy.focus.seconds=Math.floor(elapsed(copy.focus,now));copy.focus.started=null}return {format:'balthazar-backup',version:1,exportedAt:new Date(now).toISOString(),state:copy}}
export function parseBackup(value:unknown):State{
 const envelope=z.object({format:z.literal('balthazar-backup'),version:z.literal(1),exportedAt:z.string().datetime(),state:schema}).safeParse(value);
 if(!envelope.success)throw Error('Respaldo inválido o versión no compatible.');
 const s=envelope.data.state as State,taskIds=new Set(s.tasks.map(t=>t.id)),projects=new Set(s.projects.map(p=>p.id));
 if(taskIds.size!==s.tasks.length||projects.size!==s.projects.length||new Set(s.rewards.map(r=>r.id)).size!==s.rewards.length||new Set(s.redemptions.map(r=>r.id)).size!==s.redemptions.length)throw Error('El respaldo contiene identificadores duplicados.');
 const valid=(ref:string)=>!ref||taskIds.has(ref);
 if(!s.days[s.lastDay]||Object.keys(s.days).length>10000||s.lastDay<'2020-01-01'||s.lastDay>new Date().toISOString().slice(0,10)||s.tasks.some(t=>!valid(t.dependency)||t.dependency===t.id||(t.projectId&&!projects.has(t.projectId))||t.stepsDone>t.steps.length)||s.sessions.some(x=>!taskIds.has(x.taskId))||Object.values(s.days).some(d=>[...d.done,...d.missions].some(ref=>!valid(ref)))||(s.focus&&!taskIds.has(s.focus.taskId)))throw Error('El respaldo contiene referencias o fechas inválidas.');
 const dependencies=new Map(s.tasks.map(t=>[t.id,t.dependency]));for(const task of s.tasks){const seen=new Set<string>();let ref=task.id;while(ref){if(seen.has(ref))throw Error('El respaldo contiene dependencias circulares.');seen.add(ref);ref=dependencies.get(ref)||''}}
 if(s.focus){s.focus.seconds=Math.min(s.focus.seconds,s.focus.target);s.focus.started=null}return s;
}
