import {canonical,dayKey,type State,type Command} from '../app/lib/domain.ts';
import {shiftDate,saveRoutine} from './routines.ts';
export const routinePacks=[{id:'light-week',name:'Mi semana ligera'},{id:'observe-three',name:'Observar tres días'}];
export function routinePackItems(packId:string,date:string,area='Personal',projectId=''){
 const base={area,projectId,startDate:date,description:'',minutes:5,briefMinutes:2};
 if(packId==='light-week')return [{...base,title:'Caminar o hacer movimiento suave a mi ritmo',weekdays:[0,1,2,3,4,5,6],minutes:10},{...base,title:'Aprender algo y escribir una idea aplicable',weekdays:[1,4]},{...base,title:'Explicar un concepto en voz alta',weekdays:[2]},{...base,title:'Ordenar un rincón de mi espacio',weekdays:[3]},{...base,title:'Contactar a alguien importante',weekdays:[5]},{...base,title:'Revisar mi semana y elegir un enfoque',weekdays:[0]}].map((item,i)=>({...item,templateId:'light-'+i}));
 if(packId==='observe-three')return ['Observar mi día','Probar un comienzo de dos minutos','Elegir algo útil para repetir'].map((title,i)=>({...base,templateId:'observe-'+i,title,minutes:3,startDate:shiftDate(date,i),endDate:shiftDate(date,i),weekdays:[0,1,2,3,4,5,6],description:'Hoy me hizo bien… Hoy me costó… Mañana podría facilitarme las cosas haciendo… '+(i===1?'Prueba un comienzo de dos minutos.':i===2?'Revisa y elige algo útil para repetir.':'')+' Tus notas quedan fuera de Balthazar.'}));
 throw Error('Paquete inválido.');
}
export const personalRewards=[['coffee-reading','Un café y 30 minutos de lectura por gusto',150,'☕','Consumo'],['gaming','Una hora de videojuegos sin pendientes abiertos',250,'🎮','Experiencias'],['anime','Noche de anime o cine con snacks',400,'🍿','Experiencias'],['restaurant','Salir a probar un restaurante nuevo',800,'🍜','Experiencias'],['curious-book','Comprar un libro por curiosidad',1200,'📚','Productos'],['creative','Una tarde para un proyecto creativo personal',600,'🎨','Experiencias'],['massage','Una sesión de masaje o spa',1800,'🌿','Bienestar'],['daytrip','Una escapada de un día',3000,'🗺️','Experiencias'],['workspace','Mejorar un accesorio de tu espacio de trabajo',5000,'💻','Productos'],['weekend','Un fin de semana de desconexión',8000,'🌄','Experiencias']].map(([id,name,cost,emoji,category])=>({id:String(id),name:String(name),cost:Number(cost),emoji:String(emoji),category:String(category),goal:false}));
export function applyPersonalPack(s:State,a:Command,now:number){if(a.type==='routinePack'){if(!routinePacks.some(p=>p.id===a.packId))throw Error('Paquete inválido.');if(s.installedRoutinePacks!.includes(String(a.packId)))return;if(a.templateDate!==dayKey(now,s.profile.timezone))throw Error('Cambió la fecha local. Vuelve a abrir el paquete para revisar sus fechas.');if(!Array.isArray(a.items)||!a.items.length||a.items.length>6)throw Error('Selecciona acciones del paquete.');const templates=routinePackItems(String(a.packId),dayKey(now,s.profile.timezone));const seen=new Set<string>();for(const item of a.items){if(!item||typeof item!=='object')throw Error('Acción inválida.');const raw=item as Record<string,unknown>;const template=templates.find(t=>t.templateId===raw.templateId);if(!template||seen.has(template.templateId))throw Error('Selección inválida.');seen.add(template.templateId);saveRoutine(s,{...template,area:raw.area,projectId:raw.projectId,weekdays:raw.weekdays,minutes:raw.minutes,briefMinutes:raw.briefMinutes})}s.installedRoutinePacks!.push(String(a.packId));return}if(a.packId!=='personal-rewards')throw Error('Paquete inválido.');if(s.installedRewardPacks!.includes(a.packId))return;if(!Array.isArray(a.rewardIds)||!a.rewardIds.length||a.rewardIds.length>10||new Set(a.rewardIds).size!==a.rewardIds.length)throw Error('Selecciona recompensas distintas.');for(const id of a.rewardIds){const reward=personalRewards.find(r=>r.id===id);if(!reward)throw Error('Recompensa inválida.');if(!s.rewards.some(r=>canonical(r.name)===canonical(reward.name))){if(s.rewards.length>=2000)throw Error('Máximo 2000 recompensas.');s.rewards.push({...reward,id:crypto.randomUUID()})}}s.installedRewardPacks!.push(a.packId)}
