import {z} from 'zod';
import {dayKey,type State,type Command} from '../app/lib/domain.ts';
export function validRoutineDate(v:string){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v}
const date=z.string().refine(validRoutineDate,'Revisa la fecha.');
export const routineSchema=z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(160),description:z.string().max(1000).default(''),area:z.string().min(1).max(80),projectId:z.string().max(100).default(''),weekdays:z.array(z.number().int().min(0).max(6)).min(1).max(7).refine(v=>new Set(v).size===v.length),startDate:date,endDate:date.optional(),minutes:z.number().int().min(1).max(120),briefMinutes:z.number().int().min(1).max(120),status:z.enum(['active','paused'])}).strict().refine(v=>v.briefMinutes<=v.minutes&&(!v.endDate||v.endDate>=v.startDate),'Revisa las duraciones o el intervalo.').refine(v=>!v.endDate||Array.from({length:Math.min(7,Math.floor((Date.parse(v.endDate+'T12:00:00Z')-Date.parse(v.startDate+'T12:00:00Z'))/86400000)+1)},(_,i)=>(new Date(v.startDate+'T12:00:00Z').getUTCDay()+i)%7).some(d=>v.weekdays.includes(d)),'El calendario debe incluir al menos un día.');
export type Routine=z.infer<typeof routineSchema>;
export const routineEntrySchema=z.object({routineId:z.string().min(1).max(100),date,status:z.enum(['completed','skipped']),mode:z.enum(['normal','brief']),title:z.string().min(1).max(160),minutes:z.number().int().min(0).max(120),at:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER)}).strict().refine(e=>e.status==='skipped'?e.minutes===0:e.minutes>=1,'Duración del registro inválida.');
export type RoutineEntry=z.infer<typeof routineEntrySchema>;
export function shiftDate(date:string,days:number){return new Date(Date.parse(date+'T12:00:00Z')+days*86400000).toISOString().slice(0,10)}
export function scheduled(r:Routine,date:string){return r.status==='active'&&date>=r.startDate&&(!r.endDate||date<=r.endDate)&&r.weekdays.includes(new Date(date+'T12:00:00Z').getUTCDay())}
export type RoutinePreview=Omit<Routine,'id'|'status'>&{id?:string;status?:Routine['status']};
export function weeklyRoutineLoad(routines:Routine[],monday:string,proposed:RoutinePreview[]=[],replaceId?:string){
 const preview=[...routines.filter(r=>r.id!==replaceId),...proposed.map(r=>({...r,id:r.id||'preview',status:r.status||'active' as const}))];
 return Array.from({length:7},(_,i)=>{const date=shiftDate(monday,i);return {date,minutes:preview.filter(r=>scheduled(r,date)).reduce((sum,r)=>sum+r.minutes,0)}})
}
export function todayRoutines(s:State,now=Date.now()){const date=dayKey(now,s.profile.timezone);return (s.routines||[]).filter(r=>scheduled(r,date)).map(r=>({routine:r,entry:(s.routineEntries||[]).find(e=>e.routineId===r.id&&e.date===date)}))}
export function routineContext(s:State,now=Date.now()){return todayRoutines(s,now).slice(0,20).map(({routine:r,entry})=>({title:r.title,minutes:r.minutes,briefMinutes:r.briefMinutes,status:entry?.status||'unrecorded',mode:entry?.mode||null}))}
export function normalizeRoutines(s:State,now:number){s.routines??=[];s.routineEntries??=[];s.installedRoutinePacks??=[];s.installedRewardPacks??=[];const cutoff=shiftDate(dayKey(now,s.profile.timezone),-365);s.routineEntries=s.routineEntries.filter(e=>e.date>=cutoff)}
export function validateRoutineReferences(s:State){for(const markers of [s.installedRoutinePacks||[],s.installedRewardPacks||[]])if(new Set(markers).size!==markers.length)throw Error('Paquetes duplicados.');if(new Set(s.routines?.map(r=>r.id)).size!==(s.routines?.length||0))throw Error('Rutinas duplicadas.');for(const r of s.routines||[])if(!s.areas.includes(r.area)||(r.projectId&&!s.projects.some(p=>p.id===r.projectId)))throw Error('Revisa el área o proyecto de la rutina.');const pairs=new Set<string>();for(const e of s.routineEntries||[]){const pair=e.routineId+'|'+e.date;if(e.date>dayKey(Date.now(),s.profile.timezone)||!(s.routines||[]).some(r=>r.id===e.routineId)||pairs.has(pair))throw Error('Registros de rutina inválidos.');pairs.add(pair)}}
export function saveRoutine(s:State,a:Record<string,unknown>){const existing=a.routineId?s.routines!.find(r=>r.id===a.routineId):undefined;if(a.routineId&&!existing)throw Error('La rutina no existe.');if(!existing&&s.routines!.length>=100)throw Error('Máximo 100 rutinas.');const parsed=routineSchema.safeParse({id:existing?.id||crypto.randomUUID(),title:a.title,description:a.description||'',area:a.area|| (s.areas.includes('Personal')?'Personal':s.areas[0]),projectId:a.projectId||'',weekdays:a.weekdays,startDate:a.startDate,endDate:a.endDate||undefined,minutes:a.minutes,briefMinutes:a.briefMinutes,status:existing?.status||'active'});if(!parsed.success)throw Error('Revisa los datos de la rutina.');const r=parsed.data;if(!s.areas.includes(r.area)||(r.projectId&&!s.projects.some(p=>p.id===r.projectId)))throw Error('Revisa el área o proyecto.');if(existing)Object.assign(existing,r);else s.routines!.push(r)}
export function applyRoutine(s:State,a:Command,now:number){if(a.type==='routine'){saveRoutine(s,a);return}const r=s.routines!.find(r=>r.id===a.routineId);if(!r)throw Error('La rutina no existe.');if(a.type==='routineStatus'){if(a.status!=='active'&&a.status!=='paused')throw Error('Estado inválido.');r.status=a.status;return}const date=dayKey(now,s.profile.timezone);if(a.date!==date)throw Error('Solo puedes registrar o corregir hoy.');const old=s.routineEntries!.find(e=>e.routineId===r.id&&e.date===date);if(a.status==='clear'){if(!old)throw Error('No hay registro que corregir.');s.routineEntries=s.routineEntries!.filter(e=>e!==old);return}if(!scheduled(r,date))throw Error('Esta rutina no está programada hoy.');if(a.status!=='completed'&&a.status!=='skipped')throw Error('Registro inválido.');if(a.mode!==undefined&&a.mode!=='normal'&&a.mode!=='brief')throw Error('Modalidad inválida.');const mode=a.mode==='brief'?'brief':'normal';const entry:RoutineEntry={routineId:r.id,date,status:a.status,mode,title:r.title,minutes:a.status==='skipped'?0:mode==='brief'?r.briefMinutes:r.minutes,at:now};if(old)Object.assign(old,entry);else s.routineEntries!.push(entry)}
